from __future__ import annotations

LEAGUE_GROUP_SIZE: int = 20
LEAGUE_MATCHES_PER_CLUB: int = 38
LEAGUE_MATCH_WINDOWS_PER_DAY: int = 6

MATCH_PRESENTATION_MIN_MINUTES: int = 3
MATCH_PRESENTATION_MAX_MINUTES: int = 5
FINAL_PRESENTATION_MAX_MINUTES: int = 10
HALFTIME_ANALYSIS_MIN_SECONDS: int = 60
HALFTIME_ANALYSIS_MAX_SECONDS: int = 120
HIGHLIGHT_DEFAULT_EXPIRY_SECONDS: int = 600

WORLD_SUPER_CUP_MAIN_TEAMS: int = 32
WORLD_SUPER_CUP_DIRECT_SLOTS: int = 24
WORLD_SUPER_CUP_PLAYOFF_TEAMS: int = 16
WORLD_SUPER_CUP_PLAYOFF_WINNERS: int = 8

CHAMPIONS_LEAGUE_TOTAL_QUALIFIERS: int = 48
CHAMPIONS_LEAGUE_DIRECT_SLOTS: int = 24
CHAMPIONS_LEAGUE_PLAYOFF_SLOTS: int = 24
CHAMPIONS_LEAGUE_LEAGUE_PHASE_TEAMS: int = 36

FAST_CUP_REGISTRATION_INTERVAL_MINUTES: int = 15

LEAGUE_BUY_IN_TIERS: list[int] = [1000, 800, 500, 300, 150, 25]
ACADEMY_BUY_IN_MULTIPLIER: float = 0.5

LEAGUE_WINNER_PCT: float = 0.50
TOP_SCORER_PCT: float = 0.10
TOP_ASSIST_PCT: float = 0.05
CHAMPIONS_LEAGUE_FUND_PCT: float = 0.35

CHAMPIONS_LEAGUE_WINNER_PCT: float = 0.70
CHAMPIONS_LEAGUE_PLATFORM_PCT: float = 0.30

USER_COMPETITION_MIN_PARTICIPANTS: int = 2
USER_COMPETITION_MAX_PARTICIPANTS: int = 64

LEAGUE_RULE_WIN_POINTS_MIN: int = 1
LEAGUE_RULE_WIN_POINTS_MAX: int = 5
LEAGUE_RULE_DRAW_POINTS_MIN: int = 0
LEAGUE_RULE_DRAW_POINTS_MAX: int = 3
LEAGUE_RULE_LOSS_POINTS_MIN: int = 0
LEAGUE_RULE_LOSS_POINTS_MAX: int = 1

LEAGUE_RULE_ALLOWED_TIE_BREAKS: tuple[str, ...] = (
    "points",
    "goal_diff",
    "goals_for",
    "head_to_head",
    "fair_play",
)

CUP_ALLOWED_PARTICIPANT_SIZES: tuple[int, ...] = (4, 8, 16, 32, 64)

USER_COMPETITION_MAX_PLATFORM_FEE_BPS: int = 1500
USER_COMPETITION_MAX_HOST_CREATION_FEE_MINOR: int = 250_000
USER_COMPETITION_MAX_ENTRY_FEE_MINOR: int = 1_000_000
