from __future__ import annotations

LEAGUE_GROUP_SIZE: int = 20
LEAGUE_MATCHES_PER_CLUB: int = 38
LEAGUE_MATCH_WINDOWS_PER_DAY: int = 6

MATCH_PRESENTATION_MIN_MINUTES: int = 3
MATCH_PRESENTATION_MAX_MINUTES: int = 5
FINAL_PRESENTATION_MAX_MINUTES: int = 10

WORLD_SUPER_CUP_MAIN_TEAMS: int = 32
WORLD_SUPER_CUP_DIRECT_SLOTS: int = 24
WORLD_SUPER_CUP_PLAYOFF_TEAMS: int = 16
WORLD_SUPER_CUP_PLAYOFF_WINNERS: int = 8

CHAMPIONS_LEAGUE_TOTAL_QUALIFIERS: int = 48
CHAMPIONS_LEAGUE_DIRECT_SLOTS: int = 24
CHAMPIONS_LEAGUE_PLAYOFF_SLOTS: int = 24
CHAMPIONS_LEAGUE_LEAGUE_PHASE_TEAMS: int = 36

FAST_CUP_REGISTRATION_INTERVAL_MINUTES: int = 15

LEAGUE_BUY_IN_TIERS: list[int] = [1000, 800, 500, 300, 150, 25]
ACADEMY_BUY_IN_MULTIPLIER: float = 0.5

LEAGUE_WINNER_PCT: float = 0.50
TOP_SCORER_PCT: float = 0.10
TOP_ASSIST_PCT: float = 0.05
CHAMPIONS_LEAGUE_FUND_PCT: float = 0.35

CHAMPIONS_LEAGUE_WINNER_PCT: float = 0.70
CHAMPIONS_LEAGUE_PLATFORM_PCT: float = 0.30
