CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email citext NOT NULL UNIQUE,
    username citext NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wallets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    code text NOT NULL UNIQUE,
    asset_code text NOT NULL CHECK (asset_code IN ('GTEX', 'FAN')),
    owner_scope text NOT NULL DEFAULT 'user'
        CHECK (owner_scope IN ('user', 'platform')),
    wallet_type text NOT NULL DEFAULT 'spendable'
        CHECK (wallet_type IN ('spendable', 'escrow', 'rewards_pool', 'lottery_pool')),
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'frozen', 'closed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (owner_scope = 'user' AND user_id IS NOT NULL)
        OR (owner_scope = 'platform' AND user_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_wallets_user_asset
    ON wallets (user_id, asset_code);

CREATE TABLE IF NOT EXISTS transactions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_type text NOT NULL CHECK (
        transaction_type IN (
            'deposit',
            'withdrawal',
            'match_entry_fee',
            'match_reward',
            'lottery_reward',
            'player_share_buy',
            'player_share_sell',
            'club_share_buy',
            'club_share_payout',
            'transfer_settlement',
            'adjustment'
        )
    ),
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'committed', 'failed', 'cancelled')),
    reference_id text UNIQUE,
    external_reference text,
    initiated_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    committed_at timestamptz
);

CREATE INDEX IF NOT EXISTS ix_transactions_type_created_at
    ON transactions (transaction_type, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_transactions_status_created_at
    ON transactions (status, created_at DESC);

CREATE TABLE IF NOT EXISTS ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id uuid NOT NULL REFERENCES transactions(id) ON DELETE RESTRICT,
    wallet_id uuid NOT NULL REFERENCES wallets(id) ON DELETE RESTRICT,
    entry_type text NOT NULL CHECK (entry_type IN ('available', 'locked')),
    direction text NOT NULL CHECK (direction IN ('debit', 'credit')),
    amount_minor bigint NOT NULL CHECK (amount_minor > 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_ledger_entries_transaction_wallet
    ON ledger_entries (transaction_id, wallet_id);
CREATE INDEX IF NOT EXISTS ix_ledger_entries_wallet_created_at
    ON ledger_entries (wallet_id, created_at DESC);

CREATE TABLE IF NOT EXISTS ledger_balance_projections (
    wallet_id uuid PRIMARY KEY REFERENCES wallets(id) ON DELETE CASCADE,
    available_balance_minor bigint NOT NULL DEFAULT 0 CHECK (available_balance_minor >= 0),
    locked_balance_minor bigint NOT NULL DEFAULT 0 CHECK (locked_balance_minor >= 0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_transaction_id uuid REFERENCES transactions(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_ledger_balance_projections_last_transaction
    ON ledger_balance_projections (last_transaction_id);

CREATE TABLE IF NOT EXISTS clubs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name text NOT NULL,
    treasury_balance_minor bigint NOT NULL DEFAULT 0,
    valuation_minor bigint NOT NULL DEFAULT 0,
    reputation integer NOT NULL DEFAULT 0,
    fan_count integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_clubs_owner_id ON clubs (owner_id);
CREATE INDEX IF NOT EXISTS ix_clubs_reputation ON clubs (reputation DESC);
CREATE INDEX IF NOT EXISTS ix_clubs_fan_count ON clubs (fan_count DESC);

CREATE TABLE IF NOT EXISTS competitions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    type text NOT NULL CHECK (type IN ('league', 'cup')),
    rules jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_competitions_type_created_at
    ON competitions (type, created_at DESC);

CREATE TABLE IF NOT EXISTS players (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    type text NOT NULL CHECK (type IN ('regen', 'real')),
    name text NOT NULL,
    age integer NOT NULL CHECK (age BETWEEN 14 AND 60),
    rating integer NOT NULL CHECK (rating BETWEEN 0 AND 100),
    potential integer NOT NULL CHECK (potential BETWEEN 0 AND 100 AND potential >= rating),
    position text NOT NULL,
    club_id uuid REFERENCES clubs(id) ON DELETE SET NULL,
    base_value_minor bigint NOT NULL CHECK (base_value_minor >= 0),
    current_value_minor bigint NOT NULL DEFAULT 0 CHECK (current_value_minor >= 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_players_club_position_rating
    ON players (club_id, position, rating DESC);
CREATE INDEX IF NOT EXISTS ix_players_type_rating
    ON players (type, rating DESC);

CREATE TABLE IF NOT EXISTS player_meta (
    player_id uuid PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
    emotional_state jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_player_meta_attributes_gin
    ON player_meta USING GIN (attributes jsonb_path_ops);

CREATE TABLE IF NOT EXISTS contracts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id uuid NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    salary bigint NOT NULL CHECK (salary >= 0),
    start_date date NOT NULL,
    end_date date NOT NULL,
    clauses jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (end_date >= start_date),
    EXCLUDE USING gist (
        player_id WITH =,
        daterange(start_date, end_date, '[]') WITH &&
    )
);

CREATE INDEX IF NOT EXISTS ix_contracts_club_end_date
    ON contracts (club_id, end_date);
CREATE INDEX IF NOT EXISTS ix_contracts_player_end_date
    ON contracts (player_id, end_date);

CREATE TABLE IF NOT EXISTS matches (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    competition_id uuid REFERENCES competitions(id) ON DELETE SET NULL,
    host_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    match_type text NOT NULL DEFAULT 'gtex_hosted'
        CHECK (match_type IN ('gtex_hosted', 'user_hosted', 'fast_match')),
    home_club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE RESTRICT,
    away_club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE RESTRICT,
    entry_fee_minor bigint NOT NULL DEFAULT 0 CHECK (entry_fee_minor >= 0),
    prize_pool_minor bigint NOT NULL DEFAULT 0 CHECK (prize_pool_minor >= 0),
    status text NOT NULL CHECK (status IN ('scheduled', 'live', 'completed', 'cancelled')),
    scheduled_at timestamptz NOT NULL,
    result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (home_club_id <> away_club_id)
);

CREATE INDEX IF NOT EXISTS ix_matches_competition_scheduled_at
    ON matches (competition_id, scheduled_at DESC);
CREATE INDEX IF NOT EXISTS ix_matches_host_user_scheduled_at
    ON matches (host_user_id, scheduled_at DESC);
CREATE INDEX IF NOT EXISTS ix_matches_status_scheduled_at
    ON matches (status, scheduled_at DESC);
CREATE INDEX IF NOT EXISTS ix_matches_home_scheduled_at
    ON matches (home_club_id, scheduled_at DESC);
CREATE INDEX IF NOT EXISTS ix_matches_away_scheduled_at
    ON matches (away_club_id, scheduled_at DESC);
CREATE INDEX IF NOT EXISTS ix_matches_live_window
    ON matches (scheduled_at)
    WHERE status IN ('scheduled', 'live');

CREATE TABLE IF NOT EXISTS match_participants (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    match_id uuid NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    club_id uuid REFERENCES clubs(id) ON DELETE SET NULL,
    side text NOT NULL CHECK (side IN ('home', 'away')),
    team_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    result text,
    joined_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (match_id, user_id)
);

CREATE INDEX IF NOT EXISTS ix_match_participants_match_side
    ON match_participants (match_id, side);
CREATE INDEX IF NOT EXISTS ix_match_participants_user_joined_at
    ON match_participants (user_id, joined_at DESC);

CREATE TABLE IF NOT EXISTS match_events (
    match_id uuid NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    minute integer NOT NULL CHECK (minute BETWEEN 0 AND 200),
    event_type text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (match_id, id)
) PARTITION BY HASH (match_id);

DO $$
DECLARE
    partition_count integer := 32;
    partition_index integer;
BEGIN
    FOR partition_index IN 0..partition_count - 1 LOOP
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS match_events_p%s PARTITION OF match_events
             FOR VALUES WITH (MODULUS %s, REMAINDER %s)',
            lpad(partition_index::text, 2, '0'),
            partition_count,
            partition_index
        );
    END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS ix_match_events_match_minute_id
    ON match_events (match_id, minute, id);
CREATE INDEX IF NOT EXISTS ix_match_events_event_type_created_at
    ON match_events (event_type, created_at DESC);

CREATE TABLE IF NOT EXISTS player_rentals (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id uuid NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tournament_id uuid NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
    price bigint NOT NULL CHECK (price >= 0),
    start_date timestamptz NOT NULL,
    end_date timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (end_date > start_date),
    EXCLUDE USING gist (
        player_id WITH =,
        tstzrange(start_date, end_date, '[)') WITH &&
    )
);

CREATE INDEX IF NOT EXISTS ix_player_rentals_user_end_date
    ON player_rentals (user_id, end_date DESC);
CREATE INDEX IF NOT EXISTS ix_player_rentals_tournament_end_date
    ON player_rentals (tournament_id, end_date DESC);

CREATE TABLE IF NOT EXISTS player_share_markets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id uuid NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    total_shares integer NOT NULL DEFAULT 1000 CHECK (total_shares > 0),
    circulating_shares integer NOT NULL DEFAULT 0
        CHECK (circulating_shares >= 0 AND circulating_shares <= total_shares),
    share_price_minor bigint NOT NULL DEFAULT 0 CHECK (share_price_minor >= 0),
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'paused', 'closed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (player_id)
);

CREATE INDEX IF NOT EXISTS ix_player_share_markets_status_created_at
    ON player_share_markets (status, created_at DESC);

CREATE TABLE IF NOT EXISTS player_share_holdings (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id uuid NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    share_count integer NOT NULL DEFAULT 0 CHECK (share_count >= 0),
    average_cost_minor bigint NOT NULL DEFAULT 0 CHECK (average_cost_minor >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (player_id, user_id)
);

CREATE INDEX IF NOT EXISTS ix_player_share_holdings_user_player
    ON player_share_holdings (user_id, player_id);

CREATE TABLE IF NOT EXISTS player_orders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    market_id uuid NOT NULL REFERENCES player_share_markets(id) ON DELETE CASCADE,
    player_id uuid NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    side text NOT NULL CHECK (side IN ('buy', 'sell')),
    shares integer NOT NULL CHECK (shares > 0),
    open_shares integer NOT NULL CHECK (open_shares >= 0 AND open_shares <= shares),
    limit_price_minor bigint NOT NULL CHECK (limit_price_minor >= 0),
    status text NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'partially_filled', 'filled', 'cancelled', 'expired', 'rejected')),
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    cancelled_at timestamptz
);

CREATE INDEX IF NOT EXISTS ix_player_orders_open_book
    ON player_orders (player_id, side, status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_player_orders_user_created_at
    ON player_orders (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS player_order_fills (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id uuid NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    buy_order_id uuid NOT NULL REFERENCES player_orders(id) ON DELETE RESTRICT,
    sell_order_id uuid NOT NULL REFERENCES player_orders(id) ON DELETE RESTRICT,
    buyer_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    seller_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    shares integer NOT NULL CHECK (shares > 0),
    price_minor bigint NOT NULL CHECK (price_minor >= 0),
    gross_amount_minor bigint NOT NULL CHECK (gross_amount_minor >= 0),
    transaction_id uuid REFERENCES transactions(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (buy_order_id <> sell_order_id),
    CHECK (buyer_user_id <> seller_user_id)
);

CREATE INDEX IF NOT EXISTS ix_player_order_fills_player_created_at
    ON player_order_fills (player_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_player_order_fills_transaction_id
    ON player_order_fills (transaction_id);

CREATE TABLE IF NOT EXISTS transfer_listings (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id uuid NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    seller_club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    base_price bigint NOT NULL CHECK (base_price >= 0),
    current_bid bigint NOT NULL DEFAULT 0 CHECK (current_bid >= 0),
    highest_bidder_club_id uuid REFERENCES clubs(id) ON DELETE SET NULL,
    expires_at timestamptz NOT NULL,
    status text NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'expired', 'accepted', 'cancelled')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (highest_bidder_club_id IS NULL OR highest_bidder_club_id <> seller_club_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_transfer_listings_one_open_per_player
    ON transfer_listings (player_id)
    WHERE status = 'open';
CREATE INDEX IF NOT EXISTS ix_transfer_listings_open_expires_at
    ON transfer_listings (expires_at)
    WHERE status = 'open';
CREATE INDEX IF NOT EXISTS ix_transfer_listings_seller_status
    ON transfer_listings (seller_club_id, status, expires_at DESC);

CREATE TABLE IF NOT EXISTS bids (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id uuid NOT NULL REFERENCES transfer_listings(id) ON DELETE CASCADE,
    bidder_club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    amount bigint NOT NULL CHECK (amount >= 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_bids_listing_created_at
    ON bids (listing_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_bids_bidder_created_at
    ON bids (bidder_club_id, created_at DESC);

CREATE TABLE IF NOT EXISTS club_listings (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    asking_price bigint NOT NULL CHECK (asking_price >= 0),
    status text NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'active', 'under_offer', 'sold', 'cancelled')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_club_listings_one_active_per_club
    ON club_listings (club_id)
    WHERE status IN ('active', 'under_offer');
CREATE INDEX IF NOT EXISTS ix_club_listings_owner_status
    ON club_listings (owner_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS club_share_markets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    total_shares integer NOT NULL DEFAULT 10000 CHECK (total_shares > 0),
    issued_shares integer NOT NULL DEFAULT 0
        CHECK (issued_shares >= 0 AND issued_shares <= total_shares),
    share_price_minor bigint NOT NULL DEFAULT 0 CHECK (share_price_minor >= 0),
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'paused', 'closed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (club_id)
);

CREATE INDEX IF NOT EXISTS ix_club_share_markets_status_created_at
    ON club_share_markets (status, created_at DESC);

CREATE TABLE IF NOT EXISTS club_share_holdings (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    share_count integer NOT NULL DEFAULT 0 CHECK (share_count >= 0),
    average_cost_minor bigint NOT NULL DEFAULT 0 CHECK (average_cost_minor >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (club_id, user_id)
);

CREATE INDEX IF NOT EXISTS ix_club_share_holdings_user_club
    ON club_share_holdings (user_id, club_id);

CREATE TABLE IF NOT EXISTS club_share_distributions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    source_type text NOT NULL,
    source_reference_id text NOT NULL,
    shareholder_pool_minor bigint NOT NULL CHECK (shareholder_pool_minor >= 0),
    creator_retained_minor bigint NOT NULL CHECK (creator_retained_minor >= 0),
    transaction_id uuid REFERENCES transactions(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (club_id, source_type, source_reference_id)
);

CREATE INDEX IF NOT EXISTS ix_club_share_distributions_club_created_at
    ON club_share_distributions (club_id, created_at DESC);

CREATE TABLE IF NOT EXISTS club_share_payouts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    distribution_id uuid NOT NULL REFERENCES club_share_distributions(id) ON DELETE CASCADE,
    holding_id uuid REFERENCES club_share_holdings(id) ON DELETE SET NULL,
    club_id uuid NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    share_count integer NOT NULL CHECK (share_count >= 0),
    payout_minor bigint NOT NULL CHECK (payout_minor >= 0),
    transaction_id uuid REFERENCES transactions(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (distribution_id, user_id)
);

CREATE INDEX IF NOT EXISTS ix_club_share_payouts_user_created_at
    ON club_share_payouts (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS season_passes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    season_id text NOT NULL,
    tier text NOT NULL CHECK (tier IN ('free', 'premium')),
    xp integer NOT NULL DEFAULT 0 CHECK (xp >= 0),
    level integer NOT NULL DEFAULT 1 CHECK (level >= 1),
    rewards jsonb NOT NULL DEFAULT '{}'::jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, season_id)
);

CREATE INDEX IF NOT EXISTS ix_season_passes_user_season
    ON season_passes (user_id, season_id);

CREATE TABLE IF NOT EXISTS season_pass_claims (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    season_pass_id uuid NOT NULL REFERENCES season_passes(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    level integer NOT NULL CHECK (level >= 1),
    reward_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    claimed_at timestamptz NOT NULL,
    UNIQUE (season_pass_id, level)
);

CREATE INDEX IF NOT EXISTS ix_season_pass_claims_user_claimed_at
    ON season_pass_claims (user_id, claimed_at DESC);

CREATE TABLE IF NOT EXISTS season_pass_xp_grants (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    season_pass_id uuid NOT NULL REFERENCES season_passes(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source_type text NOT NULL,
    amount integer NOT NULL CHECK (amount > 0),
    reference_key text NOT NULL UNIQUE,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_season_pass_xp_grants_user_created_at
    ON season_pass_xp_grants (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS lottery_runs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    winner_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source_type text NOT NULL DEFAULT 'match_volume',
    source_reference_id text,
    trigger_reference text NOT NULL UNIQUE,
    reward_minor bigint NOT NULL CHECK (reward_minor > 0),
    asset_code text NOT NULL CHECK (asset_code IN ('GTEX', 'FAN')),
    transaction_id uuid REFERENCES transactions(id) ON DELETE SET NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_lottery_runs_winner_created_at
    ON lottery_runs (winner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_lottery_runs_transaction_id
    ON lottery_runs (transaction_id);

CREATE TABLE IF NOT EXISTS stories (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    type text NOT NULL,
    entities jsonb NOT NULL DEFAULT '[]'::jsonb,
    narrative text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_stories_type_created_at
    ON stories (type, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_stories_entities_gin
    ON stories USING GIN (entities jsonb_path_ops);

CREATE TABLE IF NOT EXISTS historical_records (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    type text NOT NULL,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_historical_records_type_created_at
    ON historical_records (type, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_historical_records_data_gin
    ON historical_records USING GIN (data jsonb_path_ops);

CREATE TABLE IF NOT EXISTS follows (
    follower_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    following_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (follower_id, following_id),
    CHECK (follower_id <> following_id)
);

CREATE INDEX IF NOT EXISTS ix_follows_following_id
    ON follows (following_id);

CREATE TABLE IF NOT EXISTS activity_feed (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type text NOT NULL,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_activity_feed_user_created_at
    ON activity_feed (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_activity_feed_type_created_at
    ON activity_feed (type, created_at DESC);

CREATE TABLE IF NOT EXISTS outbox_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type text NOT NULL,
    aggregate_id uuid,
    topic text NOT NULL,
    partition_key text NOT NULL,
    event_type text NOT NULL,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'published', 'failed')),
    attempts integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz
);

CREATE INDEX IF NOT EXISTS ix_outbox_events_status_created_at
    ON outbox_events (status, created_at);
CREATE INDEX IF NOT EXISTS ix_outbox_events_topic_partition_key
    ON outbox_events (topic, partition_key, created_at);
