from __future__ import annotations

from decimal import Decimal

FOOTBALL_GIFT_CATALOG: tuple[dict[str, object], ...] = (
    {
        "key": "whistle_blow",
        "display_name": "Whistle Blow",
        "tier": "common",
        "rarity": "common",
        "fancoin_price": Decimal("1.0000"),
        "animation_key": "common_whistle",
        "sound_key": "whistle_pop",
        "duration_ms": 1200,
        "description": "A quick matchday whistle reaction.",
        "sort_order": 10,
    },
    {
        "key": "fan_chant",
        "display_name": "Fan Chant",
        "tier": "common",
        "rarity": "common",
        "fancoin_price": Decimal("2.0000"),
        "animation_key": "fan_chant",
        "sound_key": "crowd_chant",
        "duration_ms": 1600,
        "description": "A chant from the stands for a football room.",
        "sort_order": 20,
    },
    {
        "key": "goal_celebration",
        "display_name": "Goal Celebration",
        "tier": "rare",
        "rarity": "rare",
        "fancoin_price": Decimal("10.0000"),
        "animation_key": "goal_celebration",
        "sound_key": "goal_roar",
        "duration_ms": 2200,
        "description": "Ball in the net, crowd up, room buzzing.",
        "sort_order": 100,
    },
    {
        "key": "legend_card_reveal",
        "display_name": "Legend Card Reveal",
        "tier": "epic",
        "rarity": "epic",
        "fancoin_price": Decimal("150.0000"),
        "animation_key": "legend_card_reveal",
        "sound_key": "card_reveal_riser",
        "duration_ms": 3600,
        "description": "A premium football card reveal for standout moments.",
        "sort_order": 250,
    },
    {
        "key": "tactical_masterclass",
        "display_name": "Tactical Masterclass",
        "tier": "epic",
        "rarity": "epic",
        "fancoin_price": Decimal("180.0000"),
        "animation_key": "tactical_masterclass",
        "sound_key": "tactics_board_ping",
        "duration_ms": 3600,
        "description": "Formation lines and arrows for a serious tactics shout.",
        "sort_order": 260,
    },
    {
        "key": "world_best_award",
        "display_name": "World Best Award",
        "fallback_display_name": "Global Best Award",
        "tier": "legendary",
        "rarity": "legendary",
        "fancoin_price": Decimal("1200.0000"),
        "animation_key": "world_best_award",
        "sound_key": "stadium_award_roar",
        "duration_ms": 5200,
        "description": "World-stage podium lights for elite football recognition.",
        "sort_order": 600,
        "is_award_pack": True,
        "legal_status": "configurable",
    },
    {
        "key": "king_of_tactics",
        "display_name": "King of Tactics",
        "fallback_display_name": "Tactics Crown",
        "tier": "legendary",
        "rarity": "legendary",
        "fancoin_price": Decimal("1100.0000"),
        "animation_key": "king_of_tactics",
        "sound_key": "tactics_crown_hit",
        "duration_ms": 5000,
        "description": "A tactical board lights up into a crown formation.",
        "sort_order": 610,
        "is_award_pack": True,
        "legal_status": "safe",
    },
    {
        "key": "top_trainer",
        "display_name": "Top Trainer",
        "fallback_display_name": "Elite Trainer",
        "tier": "legendary",
        "rarity": "legendary",
        "fancoin_price": Decimal("950.0000"),
        "animation_key": "top_trainer",
        "sound_key": "training_whistle_rise",
        "duration_ms": 4600,
        "description": "Training cones, whistle, and rising player cards.",
        "sort_order": 620,
        "is_award_pack": True,
        "legal_status": "safe",
    },
    {
        "key": "golden_manager",
        "display_name": "Golden Manager",
        "tier": "legendary",
        "rarity": "legendary",
        "fancoin_price": Decimal("1000.0000"),
        "animation_key": "golden_manager",
        "sound_key": "dugout_spotlight",
        "duration_ms": 4800,
        "description": "Dugout spotlight, tactical notes, and trophy glow.",
        "sort_order": 630,
        "is_award_pack": True,
    },
    {
        "key": "player_of_the_match",
        "display_name": "Player of the Match",
        "tier": "epic",
        "rarity": "epic",
        "fancoin_price": Decimal("500.0000"),
        "animation_key": "player_of_the_match",
        "sound_key": "mvp_card_hit",
        "duration_ms": 4000,
        "description": "A match card spotlight with an MVP ribbon.",
        "sort_order": 640,
        "is_award_pack": True,
    },
    {
        "key": "golden_boot_king",
        "display_name": "Golden Boot King",
        "fallback_display_name": "Golden Boot Crown",
        "tier": "legendary",
        "rarity": "legendary",
        "fancoin_price": Decimal("900.0000"),
        "animation_key": "golden_boot_spark",
        "sound_key": "net_ripple_roar",
        "duration_ms": 4400,
        "description": "A golden boot strike into the net.",
        "sort_order": 650,
        "is_award_pack": True,
    },
    {
        "key": "safe_hands_award",
        "display_name": "Safe Hands Award",
        "tier": "epic",
        "rarity": "epic",
        "fancoin_price": Decimal("450.0000"),
        "animation_key": "safe_hands_award",
        "sound_key": "keeper_save_snap",
        "duration_ms": 3800,
        "description": "Goalkeeper gloves catch a glowing ball.",
        "sort_order": 660,
        "is_award_pack": True,
    },
    {
        "key": "midfield_maestro",
        "display_name": "Midfield Maestro",
        "tier": "epic",
        "rarity": "epic",
        "fancoin_price": Decimal("450.0000"),
        "animation_key": "midfield_maestro",
        "sound_key": "passing_lines_swell",
        "duration_ms": 3800,
        "description": "Passing lines across the pitch with a conductor flourish.",
        "sort_order": 670,
        "is_award_pack": True,
    },
    {
        "key": "ballon_dor",
        "display_name": "Ballon d'Or",
        "fallback_display_name": "Golden Ball Supreme",
        "tier": "mythic",
        "rarity": "mythic",
        "fancoin_price": Decimal("10000.0000"),
        "animation_key": "ballon_dor",
        "sound_key": "stadium_ceremony_roar",
        "duration_ms": 8000,
        "description": "The highest GTEX gift pack: a full stadium golden-ball ceremony.",
        "sort_order": 1000,
        "is_award_pack": True,
        "legal_status": "requires_review",
    },
)
