from __future__ import annotations

from datetime import timedelta

from app.core.config import DEFAULT_DATABASE_URL as CORE_DEFAULT_DATABASE_URL

DEFAULT_PROVIDER_NAME = "mock"
DEFAULT_CURSOR_KEY = "default"
DEFAULT_LOCK_TTL_SECONDS = 15 * 60
DEFAULT_DATABASE_URL = CORE_DEFAULT_DATABASE_URL

ENV_DATABASE_URL = "GTE_DATABASE_URL"
ENV_REDIS_URL = "GTE_REDIS_URL"
ENV_PROVIDER_NAME = "GTE_INGESTION_PROVIDER"
ENV_PROVIDER_TIMEOUT_SECONDS = "GTE_PROVIDER_TIMEOUT_SECONDS"
ENV_FOOTBALL_DATA_BASE_URL = "FOOTBALL_DATA_BASE_URL"
ENV_FOOTBALL_DATA_API_KEY = "FOOTBALL_DATA_API_KEY"
ENV_API_SPORTS_BASE_URL = "API_SPORTS_BASE_URL"
ENV_API_SPORTS_API_KEY = "API_SPORTS_API_KEY"
ENV_SPORTMONKS_BASE_URL = "SPORTMONKS_BASE_URL"
ENV_SPORTMONKS_API_TOKEN = "SPORTMONKS_API_TOKEN"

TOP_PROSPECTS_TTL_SECONDS = int(timedelta(minutes=10).total_seconds())
PLAYER_PROFILE_SUMMARY_TTL_SECONDS = int(timedelta(minutes=5).total_seconds())
TRENDING_PLAYERS_TTL_SECONDS = int(timedelta(minutes=5).total_seconds())
COMPETITION_TABLE_TTL_SECONDS = int(timedelta(minutes=3).total_seconds())
CLUB_ROSTER_SNAPSHOT_TTL_SECONDS = int(timedelta(minutes=5).total_seconds())

BOOTSTRAP_ENTITY_TYPE = "bootstrap"
INCREMENTAL_ENTITY_TYPE = "incremental"
MATCHES_ENTITY_TYPE = "match"
STANDINGS_ENTITY_TYPE = "team_standing"
PLAYER_MATCH_STATS_ENTITY_TYPE = "player_match_stat"
PLAYER_SEASON_STATS_ENTITY_TYPE = "player_season_stat"
REAL_PLAYER_IMPORT_ENTITY_TYPE = "real_player_directory"
REAL_PLAYER_IMPORT_JOB_NAME = "real_player_directory_import"
REAL_PLAYER_FILE_IMPORT_JOB_NAME = "real_player_file_import"
REAL_PLAYER_IMPORT_CURSOR_KEY = "real-player-directory"

SYNC_RUN_STATUS_RUNNING = "running"
SYNC_RUN_STATUS_SUCCESS = "success"
SYNC_RUN_STATUS_FAILED = "failed"
SYNC_RUN_STATUS_PARTIAL = "partial_success"
