from __future__ import annotations

COUNTRY_SPECIFIC_NAME_POOLS: dict[str, dict[str, object]] = {
    "AG": {
        "region": "Saint John",
        "city": "Saint John's",
        "ethno": "antiguan_barbudan",
        "pattern": "caribbean_mixed",
        "given": ("Jayden", "Malik", "Kieran", "Akeem", "Omari", "Denzel", "Andre", "Nathaniel", "Kemar", "Raheem"),
        "surnames": ("Joseph", "Francis", "Benjamin", "Thomas", "Samuel", "Simon", "Christian", "Williams", "Browne", "Lake"),
    },
    "AO": {
        "region": "Luanda",
        "city": "Luanda",
        "ethno": "angolan_lusophone",
        "pattern": "christian_lusophone",
        "given": ("Adilson", "Afonso", "Armando", "Bastos", "Claudio", "Dario", "Gelson", "Helder", "Manuel", "Mateus"),
        "surnames": ("Afonso", "Bastos", "Cafu", "Carvalho", "Costa", "Fernandes", "Manuel", "Mateus", "Silva", "dos Santos"),
    },
    "AR": {
        "region": "Buenos Aires",
        "city": "Buenos Aires",
        "ethno": "argentine_spanish",
        "pattern": "rioplatense_spanish",
        "given": ("Mateo", "Thiago", "Santiago", "Franco", "Tomas", "Benjamin", "Lautaro", "Julian", "Nicolas", "Facundo"),
        "surnames": ("Gonzalez", "Rodriguez", "Fernandez", "Lopez", "Perez", "Romero", "Acosta", "Diaz", "Rojas", "Sosa"),
    },
    "AT": {
        "region": "Vienna",
        "city": "Vienna",
        "ethno": "austrian_german",
        "pattern": "central_european",
        "given": ("Lukas", "Jakob", "David", "Maximilian", "Leon", "Felix", "Tobias", "Florian", "Matthias", "Niklas"),
        "surnames": ("Gruber", "Huber", "Bauer", "Wagner", "Muller", "Schmid", "Steiner", "Hofer", "Berger", "Fuchs"),
    },
    "BE": {
        "region": "Brussels-Capital",
        "city": "Brussels",
        "ethno": "belgian",
        "pattern": "flemish_walloon_mix",
        "given": ("Lucas", "Noah", "Louis", "Arthur", "Jules", "Mathis", "Thibaut", "Simon", "Liam", "Milan"),
        "surnames": ("Peeters", "Janssens", "Maes", "Dubois", "Mertens", "Lambert", "Willems", "Claes", "Leclercq", "Jacobs"),
    },
    "BF": {
        "region": "Centre",
        "city": "Ouagadougou",
        "ethno": "burkinabe",
        "pattern": "mande_mossi_mixed",
        "given": ("Abdoulaye", "Issouf", "Moussa", "Adama", "Ibrahim", "Oumar", "Bakary", "Lassina", "Souleymane", "Seydou"),
        "surnames": ("Kone", "Traore", "Ouattara", "Sawadogo", "Compaore", "Kabore", "Zongo", "Ouedraogo", "Bance", "Diallo"),
    },
    "BI": {
        "region": "Bujumbura Mairie",
        "city": "Bujumbura",
        "ethno": "burundian",
        "pattern": "great_lakes",
        "given": ("Cedric", "Fabrice", "Eric", "Pacifique", "Didier", "Jean-Claude", "Patrick", "Arnaud", "Kevin", "Tresor"),
        "surnames": ("Niyonzima", "Ndayishimiye", "Nkurunziza", "Bigirimana", "Nahimana", "Nsabiyumva", "Ndikumana", "Nduwimana", "Hakizimana", "Nshimirimana"),
    },
    "BJ": {
        "region": "Littoral",
        "city": "Cotonou",
        "ethno": "beninese",
        "pattern": "fon_yoruba_mixed",
        "given": ("Junior", "Marcel", "Steve", "Jodel", "Cedric", "Romuald", "Aurelien", "Mathias", "David", "Charbel"),
        "surnames": ("Adenon", "Adjou", "Dossou", "Sessegnon", "Hountondji", "Kiki", "Mounie", "Tijani", "Veron", "Assogba"),
    },
    "BQ": {
        "region": "Bonaire",
        "city": "Kralendijk",
        "ethno": "dutch_caribbean",
        "pattern": "caribbean_dutch_papiamento",
        "given": ("Jairo", "Denzel", "Quincy", "Rangelo", "Jayden", "Rayan", "Shurendley", "Richelor", "Jurnick", "Anselmo"),
        "surnames": ("Martis", "Cicilia", "Coffie", "Emerenciana", "Pourier", "Statia", "Janga", "Nicolaas", "Winklaar", "Bernabela"),
    },
    "BR": {
        "region": "Sao Paulo",
        "city": "Sao Paulo",
        "ethno": "brazilian_portuguese",
        "pattern": "lusophone_mixed",
        "given": ("Joao", "Pedro", "Gabriel", "Mateus", "Vinicius", "Caio", "Lucas", "Rafael", "Gustavo", "Felipe"),
        "surnames": ("Silva", "Santos", "Costa", "Oliveira", "Souza", "Pereira", "Almeida", "Nascimento", "Barbosa", "Rocha"),
    },
    "CD": {
        "region": "Kinshasa",
        "city": "Kinshasa",
        "ethno": "congolese_kinshasa",
        "pattern": "central_african_francophone",
        "given": ("Cedric", "Junior", "Theo", "Dieumerci", "Jonathan", "Fabrice", "Gael", "Merveille", "Patient", "Beni"),
        "surnames": ("Mbemba", "Mputu", "Bokadi", "Kalulu", "Mabiala", "Lusamba", "Kasongo", "Muleka", "Mbuyi", "Bolasie"),
    },
    "CF": {
        "region": "Bangui",
        "city": "Bangui",
        "ethno": "central_african",
        "pattern": "central_african_francophone",
        "given": ("Karl", "Cesar", "Junior", "Geoffrey", "Hilaire", "Eloge", "Axel", "Fabrice", "Marius", "Kevin"),
        "surnames": ("Kethevoama", "Youga", "Koyagbele", "Nicaise", "Nguimalet", "Yamissi", "Momi", "Kouango", "Mbotto", "Binguila"),
    },
    "CG": {
        "region": "Brazzaville",
        "city": "Brazzaville",
        "ethno": "congolese_brazzaville",
        "pattern": "central_african_francophone",
        "given": ("Prince", "Junior", "Dylan", "Mavis", "Borel", "Hardy", "Kevin", "Prestige", "Yann", "Chris"),
        "surnames": ("Makouana", "Moutou", "Bifouma", "Ndinga", "Mbemba", "Bitsindou", "Mpassi", "Moukoko", "Koubemba", "Ngoma"),
    },
    "CH": {
        "region": "Zurich",
        "city": "Zurich",
        "ethno": "swiss",
        "pattern": "multilingual_swiss",
        "given": ("Noah", "Luca", "Leon", "Nico", "David", "Jan", "Julian", "Marco", "Tim", "Yannick"),
        "surnames": ("Muller", "Meier", "Schmid", "Keller", "Weber", "Fischer", "Gerber", "Meyer", "Huber", "Baumann"),
    },
    "CI": {
        "region": "Abidjan",
        "city": "Abidjan",
        "ethno": "ivorian",
        "pattern": "mande_akan_francophone",
        "given": ("Ibrahim", "Moussa", "Ousmane", "Abdoulaye", "Amadou", "Bakary", "Yao", "Wilfried", "Franck", "Serge"),
        "surnames": ("Kone", "Traore", "Fofana", "Bamba", "Diarra", "Doumbia", "Kouame", "Konan", "Koffi", "Yapo"),
    },
    "CM": {
        "region": "Littoral",
        "city": "Douala",
        "ethno": "cameroonian",
        "pattern": "bantu_sahelian_mixed",
        "given": ("Andre", "Samuel", "Fabrice", "Stephane", "Jean", "Aboubakar", "Moussa", "Oumar", "Youssoufa", "Carlos"),
        "surnames": ("Onana", "Song", "Mbeumo", "Nkoulou", "Moukoudi", "Baleba", "Eto'o", "Oumarou", "Hamadou", "Bello"),
    },
    "CO": {
        "region": "Bogota",
        "city": "Bogota",
        "ethno": "colombian_spanish",
        "pattern": "hispanic",
        "given": ("Santiago", "Juan", "Mateo", "Sebastian", "Nicolas", "Daniel", "Andres", "Luis", "Jhon", "Kevin"),
        "surnames": ("Rodriguez", "Gomez", "Martinez", "Garcia", "Lopez", "Hernandez", "Perez", "Sanchez", "Ramirez", "Torres"),
    },
    "CU": {
        "region": "Havana",
        "city": "Havana",
        "ethno": "cuban",
        "pattern": "caribbean_hispanic",
        "given": ("Yordan", "Yunior", "Luis", "Carlos", "Jose", "Yosvani", "Ariel", "Dariel", "Yoel", "Randy"),
        "surnames": ("Rodriguez", "Perez", "Gonzalez", "Hernandez", "Garcia", "Martinez", "Diaz", "Castro", "Fernandez", "Valdes"),
    },
    "CV": {
        "region": "Praia",
        "city": "Praia",
        "ethno": "cape_verdean",
        "pattern": "lusophone_creole",
        "given": ("Dylan", "Jovane", "Garry", "Ryan", "Helio", "Patrick", "Adilson", "Kuca", "Vagner", "Diney"),
        "surnames": ("Tavares", "Varela", "Lopes", "Fernandes", "Semedo", "Monteiro", "Andrade", "Ramos", "Soares", "Pina"),
    },
    "CZ": {
        "region": "Prague",
        "city": "Prague",
        "ethno": "czech",
        "pattern": "central_european_slavic",
        "given": ("Jakub", "Jan", "Tomas", "Adam", "Matej", "Filip", "David", "Martin", "Lukas", "Vojtech"),
        "surnames": ("Novak", "Svoboda", "Novotny", "Dvorak", "Cerny", "Prochazka", "Kucera", "Vesely", "Horak", "Nemec"),
    },
    "DE": {
        "region": "Berlin",
        "city": "Berlin",
        "ethno": "german",
        "pattern": "central_european",
        "given": ("Lukas", "Jonas", "Leon", "Felix", "Max", "Tim", "Finn", "Paul", "Noah", "Elias"),
        "surnames": ("Muller", "Schmidt", "Schneider", "Fischer", "Weber", "Wagner", "Becker", "Hoffmann", "Schulz", "Koch"),
    },
    "DK": {
        "region": "Capital Region",
        "city": "Copenhagen",
        "ethno": "danish",
        "pattern": "nordic",
        "given": ("Oscar", "Noah", "William", "Lucas", "Emil", "Magnus", "Mikkel", "Frederik", "Oliver", "Mathias"),
        "surnames": ("Jensen", "Nielsen", "Hansen", "Pedersen", "Andersen", "Christensen", "Larsen", "Sorensen", "Rasmussen", "Madsen"),
    },
    "EN": {
        "region": "Greater London",
        "city": "London",
        "ethno": "english",
        "pattern": "english",
        "given": ("Oliver", "George", "Harry", "Jack", "Charlie", "Jacob", "Alfie", "Thomas", "James", "Leo"),
        "surnames": ("Smith", "Jones", "Taylor", "Brown", "Williams", "Wilson", "Johnson", "Davies", "Robinson", "Wright"),
    },
    "ES": {
        "region": "Madrid",
        "city": "Madrid",
        "ethno": "spanish",
        "pattern": "iberian_spanish",
        "given": ("Alejandro", "Mateo", "Pablo", "Hugo", "Daniel", "Adrian", "Alvaro", "Diego", "Marcos", "Nicolas"),
        "surnames": ("Garcia", "Lopez", "Martinez", "Fernandez", "Ruiz", "Navarro", "Sanchez", "Gomez", "Moreno", "Romero"),
    },
    "FR": {
        "region": "Ile-de-France",
        "city": "Paris",
        "ethno": "french",
        "pattern": "french_multicultural",
        "given": ("Lucas", "Nathan", "Theo", "Enzo", "Hugo", "Maxime", "Kylian", "Mathis", "Antoine", "Rayan"),
        "surnames": ("Martin", "Bernard", "Dubois", "Moreau", "Laurent", "Roux", "Petit", "Durand", "Leroy", "Girard"),
    },
    "GA": {
        "region": "Estuaire",
        "city": "Libreville",
        "ethno": "gabonese",
        "pattern": "central_african_francophone",
        "given": ("Junior", "Aaron", "Mario", "Axel", "Didier", "Brice", "Lloyd", "Yann", "Ulrich", "Kevin"),
        "surnames": ("Aubameyang", "Meye", "Ecuele", "Ndong", "Biyoghe", "Kanga", "Obame", "Lemina", "Bouanga", "Mouloungui"),
    },
    "GD": {
        "region": "Saint George",
        "city": "Saint George's",
        "ethno": "grenadian",
        "pattern": "caribbean_english",
        "given": ("Jamal", "Keron", "Akeem", "Denzel", "Kishon", "Romario", "Trevon", "Jason", "Shane", "Delon"),
        "surnames": ("Charles", "Lewis", "Noel", "Williams", "Thomas", "Mitchell", "Modeste", "Baptiste", "Cato", "Straker"),
    },
    "GF": {
        "region": "Cayenne",
        "city": "Cayenne",
        "ethno": "french_guianese",
        "pattern": "creole_francophone",
        "given": ("Dylan", "Yann", "Steeven", "Loic", "Kenny", "Mickael", "Warren", "Kevin", "Jean", "Ludovic"),
        "surnames": ("Contout", "Privat", "Ba", "Raban", "Solvi", "Sabas", "Colino", "Lina", "Torvic", "Biron"),
    },
    "GH": {
        "region": "Greater Accra",
        "city": "Accra",
        "ethno": "ghanaian_akan_ga",
        "pattern": "akan_ga_mixed",
        "given": ("Kwame", "Kojo", "Yaw", "Kwaku", "Emmanuel", "Samuel", "Kofi", "Daniel", "Abdul", "Jordan"),
        "surnames": ("Mensah", "Owusu", "Boateng", "Asante", "Annan", "Ofori", "Addo", "Agyemang", "Ayew", "Partey"),
    },
    "GM": {
        "region": "Banjul",
        "city": "Banjul",
        "ethno": "gambian",
        "pattern": "senegambian",
        "given": ("Musa", "Ebrima", "Lamin", "Modou", "Alieu", "Omar", "Bubacarr", "Pa", "Sainey", "Sulayman"),
        "surnames": ("Jallow", "Ceesay", "Sanyang", "Touray", "Manneh", "Njie", "Sonko", "Badjie", "Camara", "Barrow"),
    },
    "GQ": {
        "region": "Bioko Norte",
        "city": "Malabo",
        "ethno": "equatoguinean",
        "pattern": "hispanic_bantu",
        "given": ("Pablo", "Pedro", "Jose", "Federico", "Ruben", "Santiago", "Carlos", "Emilio", "Basilio", "Luis"),
        "surnames": ("Nsue", "Balboa", "Ondo", "Bikoro", "Nguema", "Obama", "Eyama", "Ela", "Mba", "Sima"),
    },
    "GW": {
        "region": "Bissau",
        "city": "Bissau",
        "ethno": "bissau_guinean",
        "pattern": "lusophone_west_african",
        "given": ("Bura", "Ze", "Carlos", "Mama", "Toni", "Romario", "Alfa", "Fali", "Sori", "Nanu"),
        "surnames": ("Sane", "Mane", "Balde", "Djalo", "Cande", "Embalo", "Camara", "Gomes", "Nanu", "Fati"),
    },
    "GY": {
        "region": "Demerara-Mahaica",
        "city": "Georgetown",
        "ethno": "guyanese",
        "pattern": "indo_afro_caribbean",
        "given": ("Keon", "Trayon", "Omari", "Akeem", "Ronaldo", "Vurlon", "Kelsey", "Daniel", "Ryan", "Nicholas"),
        "surnames": ("Williams", "Smith", "Gordon", "Norville", "Dover", "Peters", "Chand", "Persaud", "Singh", "Benjamin"),
    },
    "HR": {
        "region": "Zagreb",
        "city": "Zagreb",
        "ethno": "croatian",
        "pattern": "south_slavic",
        "given": ("Luka", "Ivan", "Marko", "Mateo", "Ante", "Josip", "Lovro", "Nikola", "Dino", "Filip"),
        "surnames": ("Horvat", "Kovacic", "Babic", "Maric", "Novak", "Jurisic", "Vukovic", "Knezevic", "Lovric", "Peric"),
    },
    "HT": {
        "region": "Ouest",
        "city": "Port-au-Prince",
        "ethno": "haitian",
        "pattern": "haitian_creole_francophone",
        "given": ("Frantz", "Steeven", "Duckens", "Wilde", "Jean", "Kervens", "Mikael", "Ronaldo", "Ricardo", "Jhondly"),
        "surnames": ("Pierrot", "Nazon", "Etienne", "Alceus", "Bellegarde", "Guerrier", "Lafrance", "Placide", "Saba", "Herivaux"),
    },
    "IT": {
        "region": "Lombardy",
        "city": "Milan",
        "ethno": "italian",
        "pattern": "italian",
        "given": ("Lorenzo", "Matteo", "Leonardo", "Andrea", "Riccardo", "Alessandro", "Francesco", "Gabriele", "Federico", "Tommaso"),
        "surnames": ("Rossi", "Russo", "Ferrari", "Esposito", "Romano", "Colombo", "Bianchi", "Ricci", "Marino", "Greco"),
    },
    "JP": {
        "region": "Tokyo",
        "city": "Tokyo",
        "ethno": "japanese",
        "pattern": "japanese",
        "given": ("Haruto", "Ren", "Kaito", "Sora", "Yuto", "Riku", "Daichi", "Takumi", "Shota", "Hayato"),
        "surnames": ("Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura", "Kobayashi", "Kato"),
    },
    "KE": {
        "region": "Nairobi County",
        "city": "Nairobi",
        "ethno": "kenyan",
        "pattern": "east_african",
        "given": ("Victor", "Brian", "Dennis", "Michael", "Kevin", "John", "Joseph", "Samuel", "Collins", "Elvis"),
        "surnames": ("Otieno", "Omondi", "Wanyama", "Odhiambo", "Mutiso", "Kiptoo", "Ochieng", "Kamau", "Maina", "Mwangi"),
    },
    "LR": {
        "region": "Montserrado",
        "city": "Monrovia",
        "ethno": "liberian",
        "pattern": "west_african_english",
        "given": ("Tonia", "Sekou", "Kpah", "Francis", "Sam", "William", "Mark", "Prince", "Patrick", "Allen"),
        "surnames": ("Tisdell", "Doe", "Weah", "Sherman", "Dweh", "Jebor", "Johnson", "Teah", "Kamara", "Kollie"),
    },
    "MA": {
        "region": "Casablanca-Settat",
        "city": "Casablanca",
        "ethno": "moroccan",
        "pattern": "maghrebi_arabic",
        "given": ("Youssef", "Ayoub", "Zakaria", "Hamza", "Rayan", "Ilyas", "Achraf", "Mehdi", "Anas", "Oussama"),
        "surnames": ("El Idrissi", "Amrani", "Bennani", "Alaoui", "Mansouri", "Haddad", "Hakimi", "Saiss", "Barkok", "En-Nesyri"),
    },
    "MF": {
        "region": "Marigot",
        "city": "Marigot",
        "ethno": "saint_martin",
        "pattern": "caribbean_francophone",
        "given": ("Dylan", "Kenny", "Mickael", "Warren", "Jordy", "Kevin", "Yann", "Mathieu", "Steeven", "Anthony"),
        "surnames": ("Richardson", "Lake", "Fleming", "Hodge", "Petit", "Gumbs", "Carty", "Brooks", "Baly", "Daniel"),
    },
    "MG": {
        "region": "Antananarivo",
        "city": "Antananarivo",
        "ethno": "malagasy",
        "pattern": "malagasy",
        "given": ("Ando", "Faneva", "Ibrahim", "Njiva", "Dax", "Mamy", "Tsiory", "Rija", "Lalaina", "Toky"),
        "surnames": ("Andriatsima", "Rakotoharimalala", "Raveloson", "Randrianarisoa", "Rakoto", "Rasolofonirina", "Razakariasa", "Andrianantenaina", "Rabe", "Ramanantsoa"),
    },
    "MQ": {
        "region": "Fort-de-France",
        "city": "Fort-de-France",
        "ethno": "martiniquais",
        "pattern": "caribbean_francophone",
        "given": ("Kevin", "Steeven", "Mickael", "Yann", "Jordy", "Loic", "Warren", "Dylan", "Jean", "Anthony"),
        "surnames": ("Reuperne", "Lina", "Pastel", "Cretinoir", "Cesar", "Delem", "Porsan-Clemente", "Arquin", "Dunon", "Mandouki"),
    },
    "MR": {
        "region": "Nouakchott",
        "city": "Nouakchott",
        "ethno": "mauritanian",
        "pattern": "sahelian_arabic",
        "given": ("Aboubakar", "Moulaye", "Mamadou", "El Hacen", "Aly", "Cheikh", "Souleymane", "Boubacar", "Ibrahima", "Oumar"),
        "surnames": ("Ba", "Dia", "Diop", "Sarr", "Kane", "Ndiaye", "M'Bareck", "Tanjy", "Abeid", "Guidileye"),
    },
    "MU": {
        "region": "Port Louis",
        "city": "Port Louis",
        "ethno": "mauritian",
        "pattern": "indo_creole_mauritian",
        "given": ("Kevin", "Jonathan", "Ashley", "Christopher", "Dylan", "Jean", "Jason", "Ryan", "Warren", "Adrien"),
        "surnames": ("Appadoo", "Beni", "Dina", "Francois", "Gungadin", "Joomun", "L'Enclume", "Mervin", "Rose", "Sophie"),
    },
    "MX": {
        "region": "Mexico City",
        "city": "Mexico City",
        "ethno": "mexican",
        "pattern": "hispanic",
        "given": ("Santiago", "Mateo", "Diego", "Emiliano", "Sebastian", "Gael", "Angel", "Luis", "Carlos", "Jorge"),
        "surnames": ("Hernandez", "Garcia", "Martinez", "Lopez", "Gonzalez", "Perez", "Rodriguez", "Sanchez", "Ramirez", "Cruz"),
    },
    "MZ": {
        "region": "Maputo",
        "city": "Maputo",
        "ethno": "mozambican",
        "pattern": "lusophone_african",
        "given": ("Domingues", "Luis", "Nelson", "Geny", "Reinildo", "Edson", "Manuel", "Telinho", "Claudio", "Avelino"),
        "surnames": ("Mexer", "Mandava", "Catamo", "Pelembe", "Simao", "Malembana", "Domingos", "Miquissone", "Guirrugo", "Muiomo"),
    },
    "NC": {
        "region": "South Province",
        "city": "Noumea",
        "ethno": "new_caledonian",
        "pattern": "kanak_french",
        "given": ("Georges", "Jean", "Cesar", "Bertrand", "Jordy", "Kevin", "Willy", "Mickael", "Cedric", "Yohan"),
        "surnames": ("Gope-Fenepej", "Wakanumune", "Bearune", "Kauma", "Sele", "Wajoka", "Ixoee", "Bako", "Hmae", "Kotra"),
    },
    "NE": {
        "region": "Niamey",
        "city": "Niamey",
        "ethno": "nigerien",
        "pattern": "sahelian",
        "given": ("Moussa", "Oumarou", "Amadou", "Issoufou", "Ibrahim", "Abdoulaye", "Souleymane", "Mahamane", "Boubacar", "Yacouba"),
        "surnames": ("Mahamadou", "Oumarou", "Issoufou", "Garba", "Moussa", "Ibrahim", "Soumana", "Tanimou", "Kourouma", "Adamou"),
    },
    "NG": {
        "region": "Lagos",
        "city": "Lagos",
        "ethno": "nigerian",
        "pattern": "yoruba_igbo_hausa_mix",
        "given": ("Oluwaseun", "Ayomide", "Damilola", "Kelechi", "Chinedu", "Ifeanyi", "Ibrahim", "Musa", "Aminu", "Samuel"),
        "surnames": ("Adebayo", "Balogun", "Adeyemi", "Okeke", "Eze", "Okafor", "Bello", "Garba", "Suleiman", "Olatunji"),
    },
    "NL": {
        "region": "North Holland",
        "city": "Amsterdam",
        "ethno": "dutch",
        "pattern": "dutch",
        "given": ("Daan", "Sem", "Lars", "Bram", "Luuk", "Mees", "Jesse", "Finn", "Milan", "Noah"),
        "surnames": ("de Jong", "Jansen", "de Vries", "van Dijk", "Bakker", "Visser", "Smit", "Meijer", "de Boer", "Mulder"),
    },
    "NO": {
        "region": "Oslo",
        "city": "Oslo",
        "ethno": "norwegian",
        "pattern": "nordic",
        "given": ("Jakob", "Emil", "Noah", "Oliver", "William", "Magnus", "Aksel", "Henrik", "Sander", "Mathias"),
        "surnames": ("Hansen", "Johansen", "Olsen", "Larsen", "Andersen", "Pedersen", "Nilsen", "Kristiansen", "Berg", "Dahl"),
    },
    "PS": {
        "region": "Ramallah",
        "city": "Ramallah",
        "ethno": "palestinian",
        "pattern": "levantine_arabic",
        "given": ("Mohammed", "Ahmed", "Mahmoud", "Oday", "Tamer", "Saleh", "Musa", "Yaser", "Khaled", "Omar"),
        "surnames": ("Abu Ali", "Darwish", "Maraaba", "Qumbor", "Younis", "Siam", "Hamed", "Saleh", "Khalil", "Rashid"),
    },
    "PT": {
        "region": "Lisbon",
        "city": "Lisbon",
        "ethno": "portuguese",
        "pattern": "iberian_portuguese",
        "given": ("Joao", "Diogo", "Tiago", "Goncalo", "Andre", "Rafael", "Miguel", "Tomas", "Afonso", "Rodrigo"),
        "surnames": ("Silva", "Santos", "Ferreira", "Pereira", "Costa", "Oliveira", "Rodrigues", "Martins", "Jesus", "Sousa"),
    },
    "RS": {
        "region": "Belgrade",
        "city": "Belgrade",
        "ethno": "serbian",
        "pattern": "south_slavic",
        "given": ("Luka", "Nikola", "Marko", "Stefan", "Milan", "Dusan", "Aleksandar", "Nemanja", "Filip", "Uros"),
        "surnames": ("Jovic", "Mitrovic", "Savic", "Ilic", "Petrovic", "Milenkovic", "Nikolic", "Stojanovic", "Pavlovic", "Tadic"),
    },
    "RW": {
        "region": "Kigali",
        "city": "Kigali",
        "ethno": "rwandan",
        "pattern": "great_lakes",
        "given": ("Emmanuel", "Eric", "Patrick", "Djihad", "Yannick", "Olivier", "Jean", "Kevin", "Muhadjiri", "Innocent"),
        "surnames": ("Kagere", "Bizimana", "Niyonzima", "Manzi", "Mugisha", "Mutsinzi", "Sugira", "Nsabimana", "Rwatubyaye", "Sibomana"),
    },
    "SE": {
        "region": "Stockholm",
        "city": "Stockholm",
        "ethno": "swedish",
        "pattern": "nordic",
        "given": ("William", "Liam", "Noah", "Lucas", "Elias", "Oliver", "Hugo", "Oscar", "Viktor", "Isak"),
        "surnames": ("Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsson", "Persson", "Svensson", "Gustafsson"),
    },
    "SL": {
        "region": "Western Area",
        "city": "Freetown",
        "ethno": "sierra_leonean",
        "pattern": "west_african_english",
        "given": ("Mohamed", "Alhassan", "Ibrahim", "Mustapha", "Abu", "Sorie", "Kamil", "Kwame", "John", "Lansana"),
        "surnames": ("Kamara", "Bangura", "Sesay", "Koroma", "Conteh", "Kallon", "Turay", "Dumbuya", "Kanu", "Sankoh"),
    },
    "SN": {
        "region": "Dakar",
        "city": "Dakar",
        "ethno": "senegalese",
        "pattern": "senegambian",
        "given": ("Mamadou", "Ousmane", "Ibrahima", "Cheikh", "Pape", "Abdoulaye", "Ismaila", "Sadio", "Idrissa", "Habib"),
        "surnames": ("Diop", "Ndiaye", "Sarr", "Faye", "Seck", "Ndour", "Gueye", "Mendy", "Ciss", "Diallo"),
    },
    "ST": {
        "region": "Agua Grande",
        "city": "Sao Tome",
        "ethno": "sao_tomean",
        "pattern": "lusophone_creole",
        "given": ("Jocy", "Luis", "Edivaldo", "Ricardo", "Aldair", "Jair", "Harramiz", "Edson", "Joao", "Miguel"),
        "surnames": ("Ramos", "Varela", "Fernandes", "Soares", "Pinto", "Leal", "Cardoso", "Pires", "Costa", "Santos"),
    },
    "SY": {
        "region": "Damascus",
        "city": "Damascus",
        "ethno": "syrian",
        "pattern": "levantine_arabic",
        "given": ("Omar", "Mahmoud", "Ahmad", "Mohammad", "Abdulrahman", "Khaled", "Youssef", "Firas", "Alaa", "Tamer"),
        "surnames": ("Al-Mawas", "Al-Ahmad", "Al-Soma", "Mardikian", "Khribin", "Osman", "Haj Mohamad", "Khatib", "Hamwi", "Shami"),
    },
    "TD": {
        "region": "N'Djamena",
        "city": "N'Djamena",
        "ethno": "chadian",
        "pattern": "sahelian_central_african",
        "given": ("Ezechiel", "Marius", "Casimir", "Mahamat", "Abakar", "Youssouf", "Karl", "Azrack", "Ali", "Hassan"),
        "surnames": ("N'Douassel", "Ebangue", "Mahamat", "Abderamane", "Hissein", "Youssouf", "Abakar", "Betoligar", "Mbang", "Ndoram"),
    },
    "TG": {
        "region": "Maritime",
        "city": "Lome",
        "ethno": "togolese",
        "pattern": "ewe_kabye_francophone",
        "given": ("Emmanuel", "Serge", "Kodjo", "Kossi", "Alaixys", "Floyd", "Kevin", "Mawouna", "Marouf", "Samuel"),
        "surnames": ("Adebayor", "Dossevi", "Atakora", "Akoriko", "Romao", "Wome", "Agassa", "Klidje", "Bebou", "Aziangbe"),
    },
    "TM": {
        "region": "Ashgabat",
        "city": "Ashgabat",
        "ethno": "turkmen",
        "pattern": "turkic_central_asian",
        "given": ("Myrat", "Serdar", "Arslan", "Begmyrat", "Ruslan", "Maksat", "Suleyman", "Didar", "Azat", "Vepa"),
        "surnames": ("Yakshyyew", "Annayew", "Atayew", "Geldiyew", "Orazow", "Muhadow", "Mingazow", "Bayramow", "Sapargulyyew", "Tirkisow"),
    },
    "TR": {
        "region": "Istanbul",
        "city": "Istanbul",
        "ethno": "turkish",
        "pattern": "turkish",
        "given": ("Ahmet", "Mehmet", "Yusuf", "Emre", "Arda", "Kerem", "Burak", "Mert", "Ozan", "Enes"),
        "surnames": ("Yilmaz", "Kaya", "Demir", "Sahin", "Celik", "Aydin", "Yildiz", "Arslan", "Dogan", "Kilic"),
    },
    "TT": {
        "region": "Port of Spain",
        "city": "Port of Spain",
        "ethno": "trinidadian_tobagonian",
        "pattern": "indo_afro_caribbean",
        "given": ("Keron", "Levi", "Akeem", "Kevon", "Jomal", "Hashim", "Denzil", "Kadeem", "Nathaniel", "Tristan"),
        "surnames": ("Jones", "Garcia", "Phillip", "Bateau", "Cummings", "Hackshaw", "Telfer", "Winchester", "Peltier", "Muckette"),
    },
    "TZ": {
        "region": "Dar es Salaam",
        "city": "Dar es Salaam",
        "ethno": "tanzanian",
        "pattern": "swahili_east_african",
        "given": ("Simon", "Mbwana", "Himid", "John", "Erasto", "Feisal", "Shomari", "Farid", "Kelvin", "Aishi"),
        "surnames": ("Samata", "Msuva", "Mao", "Mwamnyeto", "Kapombe", "Manula", "Yondani", "Kaseke", "Mugalu", "Kibwana"),
    },
    "US": {
        "region": "New York",
        "city": "New York",
        "ethno": "american",
        "pattern": "american_multicultural",
        "given": ("Aiden", "Noah", "Mason", "Liam", "Ethan", "Logan", "Jaylen", "Malik", "Diego", "Mateo"),
        "surnames": ("Johnson", "Williams", "Miller", "Davis", "Brown", "Wilson", "Jackson", "Robinson", "Garcia", "Martinez"),
    },
    "UY": {
        "region": "Montevideo",
        "city": "Montevideo",
        "ethno": "uruguayan",
        "pattern": "rioplatense_spanish",
        "given": ("Santiago", "Facundo", "Matias", "Agustin", "Nicolas", "Rodrigo", "Federico", "Joaquin", "Thiago", "Bruno"),
        "surnames": ("Rodriguez", "Gonzalez", "Martinez", "Fernandez", "Silva", "Pereira", "Perez", "Sosa", "Suarez", "Cavani"),
    },
    "ZM": {
        "region": "Lusaka",
        "city": "Lusaka",
        "ethno": "zambian",
        "pattern": "southern_african",
        "given": ("Patson", "Fashion", "Enock", "Emmanuel", "Edward", "Brian", "Kelvin", "Lubambo", "Clatous", "Kennedy"),
        "surnames": ("Daka", "Sakala", "Mwepu", "Banda", "Mulenga", "Kangwa", "Mwape", "Sunzu", "Chama", "Sakala"),
    },
    "ZW": {
        "region": "Harare",
        "city": "Harare",
        "ethno": "zimbabwean",
        "pattern": "southern_african",
        "given": ("Knowledge", "Marvelous", "Marshall", "Tino", "Khama", "Prince", "Kudakwashe", "Tendayi", "Walter", "Gerald"),
        "surnames": ("Musona", "Nakamba", "Billiat", "Kadewere", "Darikwa", "Mapeza", "Chimedza", "Chirambadare", "Rusike", "Munyai"),
    },
}

COUNTRY_NAME_PROFILE_ALIASES: dict[str, str] = {
    "bonaire": "BQ",
    "cote d'ivoire": "CI",
    "cote divoire": "CI",
    "ivory coast": "CI",
    "england": "EN",
}
