import 'package:gte_frontend/features/match_center/presentation/broadcast_package_models.dart';
import 'package:gte_frontend/features/match_center/models/match_event.dart';
import 'package:gte_frontend/features/match_center/models/match_timeline_frame.dart';
import 'package:gte_frontend/features/match_center/models/match_view_state.dart';

MatchViewState buildBroadcastTestViewState({
  bool scoreless = false,
  bool includeMonetization = false,
  MatchPresentationPackage? presentationPackage,
}) {
  const MatchViewerTeam homeTeam = MatchViewerTeam(
    teamId: 'home',
    teamName: 'Lagos Stars',
    shortName: 'LAG',
    side: MatchViewerSide.home,
    formation: '4-3-3',
    primaryColorHex: '#14532D',
    secondaryColorHex: '#F8FAFC',
    accentColorHex: '#22C55E',
    goalkeeperColorHex: '#0F172A',
  );
  const MatchViewerTeam awayTeam = MatchViewerTeam(
    teamId: 'away',
    teamName: 'Abuja City',
    shortName: 'ABJ',
    side: MatchViewerSide.away,
    formation: '4-3-3',
    primaryColorHex: '#991B1B',
    secondaryColorHex: '#FFF7ED',
    accentColorHex: '#F97316',
    goalkeeperColorHex: '#111827',
  );

  final List<MatchEvent> events =
      scoreless
          ? <MatchEvent>[
            _event(
              id: 'kickoff',
              sequence: 0,
              type: MatchViewerEventType.kickoff,
              timeSeconds: 0,
              minute: 0,
              homeScore: 0,
              awayScore: 0,
              bannerText: 'Kickoff',
              commentary: 'We are underway.',
            ),
            _event(
              id: 'attack-home',
              sequence: 1,
              type: MatchViewerEventType.attack,
              timeSeconds: 1,
              minute: 9,
              homeScore: 0,
              awayScore: 0,
              bannerText: 'Home attack',
              commentary: 'Lagos work it into the box.',
            ),
            _event(
              id: 'fulltime',
              sequence: 2,
              type: MatchViewerEventType.fulltime,
              timeSeconds: 90,
              minute: 90,
              homeScore: 0,
              awayScore: 0,
              bannerText: 'Full time',
              commentary: 'It finishes scoreless.',
            ),
          ]
          : <MatchEvent>[
            _event(
              id: 'kickoff',
              sequence: 0,
              type: MatchViewerEventType.kickoff,
              timeSeconds: 0,
              minute: 0,
              homeScore: 0,
              awayScore: 0,
              bannerText: 'Kickoff',
              commentary: 'We are underway.',
            ),
            _event(
              id: 'attack-home',
              sequence: 1,
              type: MatchViewerEventType.attack,
              timeSeconds: 0.6,
              minute: 6,
              homeScore: 0,
              awayScore: 0,
              bannerText: 'Home attack',
              commentary: 'Lagos build pressure down the right.',
            ),
            _event(
              id: 'goal-home',
              sequence: 2,
              type: MatchViewerEventType.goal,
              timeSeconds: 1,
              minute: 11,
              homeScore: 1,
              awayScore: 0,
              bannerText: 'Lagos score',
              commentary: 'Swept home at the near post.',
              reviewable: true,
              reviewDecision: 'confirmed',
              scoreCommit: 'after_review',
              teamId: 'home',
            ),
            _event(
              id: 'goal-away-disallowed',
              sequence: 3,
              type: MatchViewerEventType.goal,
              timeSeconds: 2.8,
              minute: 24,
              homeScore: 1,
              awayScore: 1,
              bannerText: 'Abuja think they are level',
              commentary: 'The flag goes up after the finish.',
              reviewable: true,
              reviewDecision: 'disallowed',
              scoreCommit: 'after_review',
              flags: const <String>['disallowed', 'offside_disallowed'],
              teamId: 'away',
            ),
            _event(
              id: 'miss-home',
              sequence: 4,
              type: MatchViewerEventType.miss,
              timeSeconds: 4,
              minute: 38,
              homeScore: 1,
              awayScore: 0,
              bannerText: 'Close again',
              commentary: 'Another chance flashes just wide.',
              teamId: 'home',
            ),
            _event(
              id: 'fulltime',
              sequence: 5,
              type: MatchViewerEventType.fulltime,
              timeSeconds: 90,
              minute: 90,
              homeScore: 1,
              awayScore: 0,
              bannerText: 'Full time',
              commentary: 'Lagos see it out.',
            ),
          ];

  final List<MatchTimelineFrame> frames =
      scoreless
          ? <MatchTimelineFrame>[
            _frame(
              id: 'f0',
              timeSeconds: 0,
              clockMinute: 0,
              phase: MatchViewerPhase.kickoff,
              homeScore: 0,
              awayScore: 0,
              activeEventId: 'kickoff',
              ball: const MatchViewerPoint(x: 50, y: 50),
              players: _players(shift: 0),
            ),
            _frame(
              id: 'f1',
              timeSeconds: 1,
              clockMinute: 8,
              phase: MatchViewerPhase.openPlay,
              homeScore: 0,
              awayScore: 0,
              activeEventId: 'attack-home',
              ball: const MatchViewerPoint(x: 58, y: 48),
              players: _players(shift: 2),
            ),
            _frame(
              id: 'f2',
              timeSeconds: 90,
              clockMinute: 90,
              phase: MatchViewerPhase.fulltime,
              homeScore: 0,
              awayScore: 0,
              activeEventId: 'fulltime',
              ball: const MatchViewerPoint(x: 50, y: 52),
              players: _players(shift: 1),
            ),
          ]
          : <MatchTimelineFrame>[
            _frame(
              id: 'f0',
              timeSeconds: 0,
              clockMinute: 0,
              phase: MatchViewerPhase.kickoff,
              homeScore: 0,
              awayScore: 0,
              activeEventId: 'kickoff',
              ball: const MatchViewerPoint(x: 50, y: 50),
              players: _players(shift: 0),
            ),
            _frame(
              id: 'f1',
              timeSeconds: 0.6,
              clockMinute: 6,
              phase: MatchViewerPhase.openPlay,
              homeScore: 0,
              awayScore: 0,
              activeEventId: 'attack-home',
              ball: const MatchViewerPoint(x: 60, y: 46),
              players: _players(shift: 3),
            ),
            _frame(
              id: 'f2',
              timeSeconds: 1.6,
              clockMinute: 14,
              phase: MatchViewerPhase.openPlay,
              homeScore: 0,
              awayScore: 0,
              activeEventId: 'goal-home',
              ball: const MatchViewerPoint(x: 70, y: 44),
              players: _players(shift: 6),
            ),
            _frame(
              id: 'f3',
              timeSeconds: 2.2,
              clockMinute: 17,
              phase: MatchViewerPhase.openPlay,
              homeScore: 1,
              awayScore: 0,
              activeEventId: 'goal-home',
              ball: const MatchViewerPoint(x: 76, y: 42),
              players: _players(shift: 8),
            ),
            _frame(
              id: 'f4',
              timeSeconds: 3,
              clockMinute: 24,
              phase: MatchViewerPhase.openPlay,
              homeScore: 1,
              awayScore: 0,
              activeEventId: 'goal-away-disallowed',
              ball: const MatchViewerPoint(x: 28, y: 56),
              players: _players(shift: 4, homeAttacking: false),
            ),
            _frame(
              id: 'f5',
              timeSeconds: 4,
              clockMinute: 37,
              phase: MatchViewerPhase.openPlay,
              homeScore: 1,
              awayScore: 0,
              activeEventId: 'miss-home',
              ball: const MatchViewerPoint(x: 68, y: 45),
              players: _players(shift: 7),
            ),
            _frame(
              id: 'f6',
              timeSeconds: 90,
              clockMinute: 90,
              phase: MatchViewerPhase.fulltime,
              homeScore: 1,
              awayScore: 0,
              activeEventId: 'fulltime',
              ball: const MatchViewerPoint(x: 50, y: 52),
              players: _players(shift: 1),
            ),
          ];

  return MatchViewState(
    matchId: scoreless ? 'scoreless-broadcast-test' : 'broadcast-test',
    source: 'fixture',
    supportsOffside: true,
    durationSeconds: 90,
    homeTeam: homeTeam,
    awayTeam: awayTeam,
    events: events,
    frames: frames,
    presentationPackage: presentationPackage ?? buildBroadcastTestPackage(),
  );
}

MatchViewState buildBackendAuthored3dQuarantineViewState({
  bool includeMonetization = false,
}) {
  final MatchViewState base = buildBroadcastTestViewState(
    includeMonetization: includeMonetization,
  );
  final MatchEvent offsideEvent = _event(
    id: 'offside-away',
    sequence: 4,
    type: MatchViewerEventType.offside,
    timeSeconds: 4,
    minute: 24,
    homeScore: 1,
    awayScore: 0,
    bannerText: 'Offside',
    commentary:
        'The assistant flag confirms Abuja were beyond the defensive line.',
    flags: const <String>['offside', 'disallowed'],
    teamId: 'away',
  );
  final List<MatchEvent> events = <MatchEvent>[
    ...base.events.where(
      (MatchEvent event) =>
          event.id != 'goal-away-disallowed' &&
          event.id != 'miss-home' &&
          event.timeSeconds < offsideEvent.timeSeconds,
    ),
    offsideEvent,
    ...base.events.where(
      (MatchEvent event) =>
          event.id != 'goal-away-disallowed' &&
          event.id != 'miss-home' &&
          event.timeSeconds > offsideEvent.timeSeconds,
    ),
  ];
  final List<MatchTimelineFrame> frames = base.frames
      .map((MatchTimelineFrame frame) {
        MatchTimelineFrame expanded = frame.copyWith(
          players: _fullSquadPlayers(
            shift: frame.timeSeconds.clamp(0, 8).toDouble(),
            homeAttacking: frame.ball.position.x >= 50,
          ),
        );

        if (frame.id == 'f2') {
          expanded = expanded.copyWith(
            overlayText: 'Checking...',
            pausePlayback: true,
            stage: MatchPlaybackStage.review,
            cameraPreset: MatchCameraPreset.varReplay,
          );
        }
        if (frame.id == 'f3') {
          expanded = expanded.copyWith(
            overlayText: 'Confirmed',
            stage: MatchPlaybackStage.decision,
            cameraPreset: MatchCameraPreset.goalCelebration,
            celebrationTeamId: 'home',
          );
        }
        if (frame.id == 'f5') {
          expanded = expanded.copyWith(
            activeEventId: 'offside-away',
            overlayText: 'OFFSIDE',
            pausePlayback: true,
            flagAnimation: true,
            stage: MatchPlaybackStage.decision,
            cameraPreset: MatchCameraPreset.assistantFlag,
          );
        }
        return expanded;
      })
      .toList(growable: false);

  return base.copyWith(
    source: 'backend-authored-3d-quarantine',
    supportsOffside: true,
    events: events,
    frames: frames,
  );
}

MatchPresentationPackage buildBroadcastTestPackage() {
  return MatchPresentationPackage(
    matchLabel: 'Lagos Stars vs Abuja City',
    home: MatchPresentationTeam(
      teamId: 'home',
      teamName: 'Lagos Stars',
      shortName: 'LAG',
      formation: '4-3-3',
      crest: const MatchPresentationCrest(
        initials: 'LS',
        primaryColorHex: '#14532D',
        secondaryColorHex: '#F8FAFC',
        accentColorHex: '#22C55E',
      ),
      primaryColorHex: '#14532D',
      secondaryColorHex: '#F8FAFC',
      accentColorHex: '#22C55E',
      coachName: 'S. Balogun',
      recentForm: 82,
      mentality: 'Positive',
      instructionSummary: const <String>[
        'High press 82',
        'Tempo 74',
        'Width 63',
      ],
      starters: const <MatchPresentationPlayer>[
        MatchPresentationPlayer(
          playerId: 'home-1',
          playerName: 'Adebayo',
          shirtNumber: 1,
          role: 'goalkeeper',
          line: 'goalkeeper',
          x: 90,
          y: 50,
          rating: 7.1,
        ),
        MatchPresentationPlayer(
          playerId: 'home-4',
          playerName: 'Okoro',
          shirtNumber: 4,
          role: 'defender',
          line: 'defense',
          x: 58,
          y: 28,
          rating: 7.3,
        ),
        MatchPresentationPlayer(
          playerId: 'home-6',
          playerName: 'Lawal',
          shirtNumber: 6,
          role: 'defender',
          line: 'defense',
          x: 58,
          y: 50,
          rating: 7.0,
        ),
        MatchPresentationPlayer(
          playerId: 'home-8',
          playerName: 'Bassey',
          shirtNumber: 8,
          role: 'midfielder',
          line: 'midfield',
          x: 40,
          y: 42,
          rating: 7.5,
        ),
        MatchPresentationPlayer(
          playerId: 'home-10',
          playerName: 'Nnamdi',
          shirtNumber: 10,
          role: 'forward',
          line: 'attack',
          x: 24,
          y: 50,
          rating: 8.1,
        ),
      ],
      bench: const <MatchPresentationPlayer>[
        MatchPresentationPlayer(
          playerId: 'home-b1',
          playerName: 'Salisu',
          shirtNumber: 12,
          role: 'goalkeeper',
        ),
        MatchPresentationPlayer(
          playerId: 'home-b2',
          playerName: 'Emeka',
          shirtNumber: 14,
          role: 'midfielder',
        ),
      ],
    ),
    away: MatchPresentationTeam(
      teamId: 'away',
      teamName: 'Abuja City',
      shortName: 'ABJ',
      formation: '4-2-3-1',
      crest: const MatchPresentationCrest(
        initials: 'AC',
        primaryColorHex: '#991B1B',
        secondaryColorHex: '#FFF7ED',
        accentColorHex: '#F97316',
      ),
      primaryColorHex: '#991B1B',
      secondaryColorHex: '#FFF7ED',
      accentColorHex: '#F97316',
      coachName: 'T. Musa',
      recentForm: 75,
      mentality: 'Balanced',
      instructionSummary: const <String>['Tempo 68', 'Defensive line 58'],
      starters: const <MatchPresentationPlayer>[
        MatchPresentationPlayer(
          playerId: 'away-1',
          playerName: 'Yusuf',
          shirtNumber: 1,
          role: 'goalkeeper',
          line: 'goalkeeper',
          x: 90,
          y: 50,
          rating: 6.9,
        ),
        MatchPresentationPlayer(
          playerId: 'away-5',
          playerName: 'Ibe',
          shirtNumber: 5,
          role: 'defender',
          line: 'defense',
          x: 58,
          y: 28,
          rating: 6.8,
        ),
        MatchPresentationPlayer(
          playerId: 'away-7',
          playerName: 'Afolabi',
          shirtNumber: 7,
          role: 'midfielder',
          line: 'midfield',
          x: 40,
          y: 42,
          rating: 7.2,
        ),
        MatchPresentationPlayer(
          playerId: 'away-9',
          playerName: 'Makanjuola',
          shirtNumber: 9,
          role: 'forward',
          line: 'attack',
          x: 24,
          y: 50,
          rating: 7.6,
        ),
      ],
      bench: const <MatchPresentationPlayer>[
        MatchPresentationPlayer(
          playerId: 'away-b1',
          playerName: 'Haruna',
          shirtNumber: 12,
          role: 'goalkeeper',
        ),
        MatchPresentationPlayer(
          playerId: 'away-b2',
          playerName: 'Bello',
          shirtNumber: 16,
          role: 'forward',
        ),
      ],
    ),
    context: const MatchContextBoard(
      competitionName: 'GTEX Premier League',
      competitionStage: 'Matchday 18',
      competitionContext: 'League table snapshot',
      venueName: 'National Stadium',
      kickoffLabel: '19:30 UTC',
      dateLabel: '30 Mar 2026',
      refereeName: 'A. Garuba',
      matchSignificance:
          'Top-four pressure and title-race implications on the night.',
      standings: <MatchStandingsEntry>[
        MatchStandingsEntry(
          teamId: 'home',
          teamName: 'Lagos Stars',
          position: 3,
          played: 17,
          points: 32,
          goalDifference: 10,
          form: 'WWDWL',
        ),
        MatchStandingsEntry(
          teamId: 'away',
          teamName: 'Abuja City',
          position: 5,
          played: 17,
          points: 29,
          goalDifference: 7,
          form: 'WDLWW',
        ),
      ],
      storylines: <String>[
        'Lagos can move into the top two with a win.',
        'Abuja arrive with momentum after back-to-back away victories.',
      ],
    ),
    reactions: const <MatchReactionCard>[
      MatchReactionCard(
        source: 'Match Desk',
        headline: 'Lineups confirmed',
        detail: 'Both coaches keep faith with the same front three.',
        tag: 'desk',
      ),
      MatchReactionCard(
        source: 'Press',
        headline: 'Title-race pressure',
        detail:
            'The desk expects a high-intensity first half because of the table pressure.',
        tag: 'press',
      ),
    ],
    ratingLeaders: const <MatchPresentationPlayer>[
      MatchPresentationPlayer(
        playerId: 'home-10',
        playerName: 'Nnamdi',
        rating: 8.1,
      ),
      MatchPresentationPlayer(
        playerId: 'away-9',
        playerName: 'Makanjuola',
        rating: 7.6,
      ),
    ],
    momentumNotes: const <String>[
      'Lagos control the right flank in the opening spell.',
      'Abuja are threatening on quick transitions.',
    ],
    coachNotes: const <String>[
      'Balogun wants the front line pressing the first pass.',
      'Musa is keeping the double pivot compact in front of the back four.',
    ],
    commentaryHighlights: const <String>[
      'The atmosphere is building as kickoff approaches under the floodlights.',
      'This fixture has a genuine top-four edge to it tonight.',
    ],
  );
}

MatchEvent _event({
  required String id,
  required int sequence,
  required MatchViewerEventType type,
  required double timeSeconds,
  required int minute,
  required int homeScore,
  required int awayScore,
  required String bannerText,
  required String commentary,
  bool reviewable = false,
  String? reviewDecision,
  String scoreCommit = 'immediate',
  List<String> flags = const <String>[],
  String? teamId,
}) {
  return MatchEvent(
    id: id,
    sequence: sequence,
    type: type,
    minute: minute,
    addedTime: 0,
    clockLabel: "${minute}'",
    timeSeconds: timeSeconds,
    homeScore: homeScore,
    awayScore: awayScore,
    bannerText: bannerText,
    commentary: commentary,
    emphasisLevel: 2,
    highlightedPlayerIds: const <String>[],
    flags: flags,
    reviewable: reviewable,
    reviewDecision: reviewDecision,
    scoreCommit: scoreCommit,
    teamId: teamId,
  );
}

MatchTimelineFrame _frame({
  required String id,
  required double timeSeconds,
  required double clockMinute,
  required MatchViewerPhase phase,
  required int homeScore,
  required int awayScore,
  required String activeEventId,
  required MatchViewerPoint ball,
  required List<MatchViewerPlayerFrame> players,
}) {
  return MatchTimelineFrame(
    id: id,
    timeSeconds: timeSeconds,
    clockMinute: clockMinute,
    phase: phase,
    homeScore: homeScore,
    awayScore: awayScore,
    homeAttacksRight: true,
    possessionSide: MatchViewerSide.home,
    activeEventId: activeEventId,
    players: players,
    ball: MatchViewerBallFrame(
      position: ball,
      ownerPlayerId: 'home-9',
      state: 'rolling',
    ),
  );
}

List<MatchViewerPlayerFrame> _players({
  required double shift,
  bool homeAttacking = true,
}) {
  final double homeLead = homeAttacking ? shift : -shift;
  final double awayLead = homeAttacking ? -shift : shift;
  return <MatchViewerPlayerFrame>[
    _player(
      playerId: 'home-1',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '1',
      role: MatchViewerRole.goalkeeper,
      line: MatchPlayerLine.goalkeeper,
      x: 10 + (homeLead * 0.1),
      y: 50,
    ),
    _player(
      playerId: 'home-4',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '4',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 28 + (homeLead * 0.3),
      y: 40,
    ),
    _player(
      playerId: 'home-9',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '9',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 58 + homeLead,
      y: 48,
      highlighted: true,
    ),
    _player(
      playerId: 'away-1',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '1',
      role: MatchViewerRole.goalkeeper,
      line: MatchPlayerLine.goalkeeper,
      x: 90 + (awayLead * 0.1),
      y: 50,
    ),
    _player(
      playerId: 'away-4',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '4',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 72 + (awayLead * 0.3),
      y: 58,
    ),
    _player(
      playerId: 'away-9',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '9',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 42 + awayLead,
      y: 54,
    ),
  ];
}

List<MatchViewerPlayerFrame> _fullSquadPlayers({
  required double shift,
  required bool homeAttacking,
}) {
  final double homeLead = homeAttacking ? shift : -shift;
  final double awayLead = homeAttacking ? -shift : shift;
  return <MatchViewerPlayerFrame>[
    _player(
      playerId: 'home-1',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '1',
      role: MatchViewerRole.goalkeeper,
      line: MatchPlayerLine.goalkeeper,
      x: 10 + homeLead * 0.1,
      y: 50,
    ),
    _player(
      playerId: 'home-2',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '2',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 28 + homeLead * 0.35,
      y: 18,
    ),
    _player(
      playerId: 'home-4',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '4',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 30 + homeLead * 0.3,
      y: 38,
    ),
    _player(
      playerId: 'home-5',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '5',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 30 + homeLead * 0.3,
      y: 62,
    ),
    _player(
      playerId: 'home-3',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '3',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 28 + homeLead * 0.35,
      y: 82,
    ),
    _player(
      playerId: 'home-6',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '6',
      role: MatchViewerRole.midfielder,
      line: MatchPlayerLine.midfield,
      x: 44 + homeLead * 0.5,
      y: 35,
    ),
    _player(
      playerId: 'home-8',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '8',
      role: MatchViewerRole.midfielder,
      line: MatchPlayerLine.midfield,
      x: 46 + homeLead * 0.45,
      y: 50,
    ),
    _player(
      playerId: 'home-10',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '10',
      role: MatchViewerRole.midfielder,
      line: MatchPlayerLine.midfield,
      x: 49 + homeLead * 0.55,
      y: 65,
      highlighted: true,
    ),
    _player(
      playerId: 'home-7',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '7',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 62 + homeLead,
      y: 24,
    ),
    _player(
      playerId: 'home-9',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '9',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 66 + homeLead,
      y: 50,
      highlighted: true,
    ),
    _player(
      playerId: 'home-11',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '11',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 62 + homeLead,
      y: 76,
    ),
    _player(
      playerId: 'away-1',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '1',
      role: MatchViewerRole.goalkeeper,
      line: MatchPlayerLine.goalkeeper,
      x: 90 + awayLead * 0.1,
      y: 50,
    ),
    _player(
      playerId: 'away-2',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '2',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 72 + awayLead * 0.35,
      y: 18,
    ),
    _player(
      playerId: 'away-4',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '4',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 70 + awayLead * 0.3,
      y: 38,
    ),
    _player(
      playerId: 'away-5',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '5',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 70 + awayLead * 0.3,
      y: 62,
    ),
    _player(
      playerId: 'away-3',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '3',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 72 + awayLead * 0.35,
      y: 82,
    ),
    _player(
      playerId: 'away-6',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '6',
      role: MatchViewerRole.midfielder,
      line: MatchPlayerLine.midfield,
      x: 56 + awayLead * 0.5,
      y: 35,
    ),
    _player(
      playerId: 'away-8',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '8',
      role: MatchViewerRole.midfielder,
      line: MatchPlayerLine.midfield,
      x: 54 + awayLead * 0.45,
      y: 50,
    ),
    _player(
      playerId: 'away-10',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '10',
      role: MatchViewerRole.midfielder,
      line: MatchPlayerLine.midfield,
      x: 51 + awayLead * 0.55,
      y: 65,
    ),
    _player(
      playerId: 'away-7',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '7',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 38 + awayLead,
      y: 24,
    ),
    _player(
      playerId: 'away-9',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '9',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 34 + awayLead,
      y: 50,
      highlighted: true,
    ),
    _player(
      playerId: 'away-11',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '11',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 38 + awayLead,
      y: 76,
    ),
  ];
}

MatchViewerPlayerFrame _player({
  required String playerId,
  required String teamId,
  required MatchViewerSide side,
  required String label,
  required MatchViewerRole role,
  required MatchPlayerLine line,
  required double x,
  required double y,
  bool highlighted = false,
}) {
  final MatchViewerPoint position = MatchViewerPoint(
    x: x.clamp(0, 100).toDouble(),
    y: y.clamp(0, 100).toDouble(),
  );
  return MatchViewerPlayerFrame(
    playerId: playerId,
    teamId: teamId,
    side: side,
    shirtNumber: int.tryParse(label),
    label: label,
    role: role,
    line: line,
    state: MatchViewerPlayerState.moving,
    active: true,
    highlighted: highlighted,
    position: position,
    anchorPosition: position,
  );
}
