import 'package:gte_frontend/models/match_event.dart';
import 'package:gte_frontend/models/match_timeline_frame.dart';
import 'package:gte_frontend/models/match_view_state.dart';

MatchViewState buildBroadcastTestViewState({
  bool scoreless = false,
}) {
  const MatchViewerTeam homeTeam = MatchViewerTeam(
    teamId: 'home',
    teamName: 'Lagos Stars',
    shortName: 'LAG',
    side: MatchViewerSide.home,
    formation: '4-3-3',
    primaryColorHex: '#14532D',
    secondaryColorHex: '#F8FAFC',
    accentColorHex: '#22C55E',
    goalkeeperColorHex: '#0F172A',
  );
  const MatchViewerTeam awayTeam = MatchViewerTeam(
    teamId: 'away',
    teamName: 'Abuja City',
    shortName: 'ABJ',
    side: MatchViewerSide.away,
    formation: '4-3-3',
    primaryColorHex: '#991B1B',
    secondaryColorHex: '#FFF7ED',
    accentColorHex: '#F97316',
    goalkeeperColorHex: '#111827',
  );

  final List<MatchEvent> events = scoreless
      ? <MatchEvent>[
          _event(
            id: 'kickoff',
            sequence: 0,
            type: MatchViewerEventType.kickoff,
            timeSeconds: 0,
            minute: 0,
            homeScore: 0,
            awayScore: 0,
            bannerText: 'Kickoff',
            commentary: 'We are underway.',
          ),
          _event(
            id: 'attack-home',
            sequence: 1,
            type: MatchViewerEventType.attack,
            timeSeconds: 1,
            minute: 9,
            homeScore: 0,
            awayScore: 0,
            bannerText: 'Home attack',
            commentary: 'Lagos work it into the box.',
          ),
          _event(
            id: 'fulltime',
            sequence: 2,
            type: MatchViewerEventType.fulltime,
            timeSeconds: 90,
            minute: 90,
            homeScore: 0,
            awayScore: 0,
            bannerText: 'Full time',
            commentary: 'It finishes scoreless.',
          ),
        ]
      : <MatchEvent>[
          _event(
            id: 'kickoff',
            sequence: 0,
            type: MatchViewerEventType.kickoff,
            timeSeconds: 0,
            minute: 0,
            homeScore: 0,
            awayScore: 0,
            bannerText: 'Kickoff',
            commentary: 'We are underway.',
          ),
          _event(
            id: 'attack-home',
            sequence: 1,
            type: MatchViewerEventType.attack,
            timeSeconds: 0.6,
            minute: 6,
            homeScore: 0,
            awayScore: 0,
            bannerText: 'Home attack',
            commentary: 'Lagos build pressure down the right.',
          ),
          _event(
            id: 'goal-home',
            sequence: 2,
            type: MatchViewerEventType.goal,
            timeSeconds: 1,
            minute: 11,
            homeScore: 1,
            awayScore: 0,
            bannerText: 'Lagos score',
            commentary: 'Swept home at the near post.',
            reviewable: true,
            reviewDecision: 'confirmed',
            scoreCommit: 'after_review',
            teamId: 'home',
          ),
          _event(
            id: 'goal-away-disallowed',
            sequence: 3,
            type: MatchViewerEventType.goal,
            timeSeconds: 2.8,
            minute: 24,
            homeScore: 1,
            awayScore: 1,
            bannerText: 'Abuja think they are level',
            commentary: 'The flag goes up after the finish.',
            reviewable: true,
            reviewDecision: 'disallowed',
            scoreCommit: 'after_review',
            flags: const <String>['disallowed', 'offside_disallowed'],
            teamId: 'away',
          ),
          _event(
            id: 'miss-home',
            sequence: 4,
            type: MatchViewerEventType.miss,
            timeSeconds: 4,
            minute: 38,
            homeScore: 1,
            awayScore: 0,
            bannerText: 'Close again',
            commentary: 'Another chance flashes just wide.',
            teamId: 'home',
          ),
          _event(
            id: 'fulltime',
            sequence: 5,
            type: MatchViewerEventType.fulltime,
            timeSeconds: 90,
            minute: 90,
            homeScore: 1,
            awayScore: 0,
            bannerText: 'Full time',
            commentary: 'Lagos see it out.',
          ),
        ];

  final List<MatchTimelineFrame> frames = scoreless
      ? <MatchTimelineFrame>[
          _frame(
            id: 'f0',
            timeSeconds: 0,
            clockMinute: 0,
            phase: MatchViewerPhase.kickoff,
            homeScore: 0,
            awayScore: 0,
            activeEventId: 'kickoff',
            ball: const MatchViewerPoint(x: 50, y: 50),
            players: _players(shift: 0),
          ),
          _frame(
            id: 'f1',
            timeSeconds: 1,
            clockMinute: 8,
            phase: MatchViewerPhase.openPlay,
            homeScore: 0,
            awayScore: 0,
            activeEventId: 'attack-home',
            ball: const MatchViewerPoint(x: 58, y: 48),
            players: _players(shift: 2),
          ),
          _frame(
            id: 'f2',
            timeSeconds: 90,
            clockMinute: 90,
            phase: MatchViewerPhase.fulltime,
            homeScore: 0,
            awayScore: 0,
            activeEventId: 'fulltime',
            ball: const MatchViewerPoint(x: 50, y: 52),
            players: _players(shift: 1),
          ),
        ]
      : <MatchTimelineFrame>[
          _frame(
            id: 'f0',
            timeSeconds: 0,
            clockMinute: 0,
            phase: MatchViewerPhase.kickoff,
            homeScore: 0,
            awayScore: 0,
            activeEventId: 'kickoff',
            ball: const MatchViewerPoint(x: 50, y: 50),
            players: _players(shift: 0),
          ),
          _frame(
            id: 'f1',
            timeSeconds: 0.6,
            clockMinute: 6,
            phase: MatchViewerPhase.openPlay,
            homeScore: 0,
            awayScore: 0,
            activeEventId: 'attack-home',
            ball: const MatchViewerPoint(x: 60, y: 46),
            players: _players(shift: 3),
          ),
          _frame(
            id: 'f2',
            timeSeconds: 1.6,
            clockMinute: 14,
            phase: MatchViewerPhase.openPlay,
            homeScore: 0,
            awayScore: 0,
            activeEventId: 'goal-home',
            ball: const MatchViewerPoint(x: 70, y: 44),
            players: _players(shift: 6),
          ),
          _frame(
            id: 'f3',
            timeSeconds: 2.2,
            clockMinute: 17,
            phase: MatchViewerPhase.openPlay,
            homeScore: 1,
            awayScore: 0,
            activeEventId: 'goal-home',
            ball: const MatchViewerPoint(x: 76, y: 42),
            players: _players(shift: 8),
          ),
          _frame(
            id: 'f4',
            timeSeconds: 3,
            clockMinute: 24,
            phase: MatchViewerPhase.openPlay,
            homeScore: 1,
            awayScore: 0,
            activeEventId: 'goal-away-disallowed',
            ball: const MatchViewerPoint(x: 28, y: 56),
            players: _players(shift: 4, homeAttacking: false),
          ),
          _frame(
            id: 'f5',
            timeSeconds: 4,
            clockMinute: 37,
            phase: MatchViewerPhase.openPlay,
            homeScore: 1,
            awayScore: 0,
            activeEventId: 'miss-home',
            ball: const MatchViewerPoint(x: 68, y: 45),
            players: _players(shift: 7),
          ),
          _frame(
            id: 'f6',
            timeSeconds: 90,
            clockMinute: 90,
            phase: MatchViewerPhase.fulltime,
            homeScore: 1,
            awayScore: 0,
            activeEventId: 'fulltime',
            ball: const MatchViewerPoint(x: 50, y: 52),
            players: _players(shift: 1),
          ),
        ];

  return MatchViewState(
    matchId: scoreless ? 'scoreless-broadcast-test' : 'broadcast-test',
    source: 'fixture',
    supportsOffside: true,
    durationSeconds: 90,
    homeTeam: homeTeam,
    awayTeam: awayTeam,
    events: events,
    frames: frames,
  );
}

MatchEvent _event({
  required String id,
  required int sequence,
  required MatchViewerEventType type,
  required double timeSeconds,
  required int minute,
  required int homeScore,
  required int awayScore,
  required String bannerText,
  required String commentary,
  bool reviewable = false,
  String? reviewDecision,
  String scoreCommit = 'immediate',
  List<String> flags = const <String>[],
  String? teamId,
}) {
  return MatchEvent(
    id: id,
    sequence: sequence,
    type: type,
    minute: minute,
    addedTime: 0,
    clockLabel: "${minute}'",
    timeSeconds: timeSeconds,
    homeScore: homeScore,
    awayScore: awayScore,
    bannerText: bannerText,
    commentary: commentary,
    emphasisLevel: 2,
    highlightedPlayerIds: const <String>[],
    flags: flags,
    reviewable: reviewable,
    reviewDecision: reviewDecision,
    scoreCommit: scoreCommit,
    teamId: teamId,
  );
}

MatchTimelineFrame _frame({
  required String id,
  required double timeSeconds,
  required double clockMinute,
  required MatchViewerPhase phase,
  required int homeScore,
  required int awayScore,
  required String activeEventId,
  required MatchViewerPoint ball,
  required List<MatchViewerPlayerFrame> players,
}) {
  return MatchTimelineFrame(
    id: id,
    timeSeconds: timeSeconds,
    clockMinute: clockMinute,
    phase: phase,
    homeScore: homeScore,
    awayScore: awayScore,
    homeAttacksRight: true,
    possessionSide: MatchViewerSide.home,
    activeEventId: activeEventId,
    players: players,
    ball: MatchViewerBallFrame(
      position: ball,
      ownerPlayerId: 'home-9',
      state: 'rolling',
    ),
  );
}

List<MatchViewerPlayerFrame> _players({
  required double shift,
  bool homeAttacking = true,
}) {
  final double homeLead = homeAttacking ? shift : -shift;
  final double awayLead = homeAttacking ? -shift : shift;
  return <MatchViewerPlayerFrame>[
    _player(
      playerId: 'home-1',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '1',
      role: MatchViewerRole.goalkeeper,
      line: MatchPlayerLine.goalkeeper,
      x: 10 + (homeLead * 0.1),
      y: 50,
    ),
    _player(
      playerId: 'home-4',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '4',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 28 + (homeLead * 0.3),
      y: 40,
    ),
    _player(
      playerId: 'home-9',
      teamId: 'home',
      side: MatchViewerSide.home,
      label: '9',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 58 + homeLead,
      y: 48,
      highlighted: true,
    ),
    _player(
      playerId: 'away-1',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '1',
      role: MatchViewerRole.goalkeeper,
      line: MatchPlayerLine.goalkeeper,
      x: 90 + (awayLead * 0.1),
      y: 50,
    ),
    _player(
      playerId: 'away-4',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '4',
      role: MatchViewerRole.defender,
      line: MatchPlayerLine.defense,
      x: 72 + (awayLead * 0.3),
      y: 58,
    ),
    _player(
      playerId: 'away-9',
      teamId: 'away',
      side: MatchViewerSide.away,
      label: '9',
      role: MatchViewerRole.forward,
      line: MatchPlayerLine.attack,
      x: 42 + awayLead,
      y: 54,
    ),
  ];
}

MatchViewerPlayerFrame _player({
  required String playerId,
  required String teamId,
  required MatchViewerSide side,
  required String label,
  required MatchViewerRole role,
  required MatchPlayerLine line,
  required double x,
  required double y,
  bool highlighted = false,
}) {
  final MatchViewerPoint position = MatchViewerPoint(
    x: x.clamp(0, 100).toDouble(),
    y: y.clamp(0, 100).toDouble(),
  );
  return MatchViewerPlayerFrame(
    playerId: playerId,
    teamId: teamId,
    side: side,
    shirtNumber: int.tryParse(label),
    label: label,
    role: role,
    line: line,
    state: MatchViewerPlayerState.moving,
    active: true,
    highlighted: highlighted,
    position: position,
    anchorPosition: position,
  );
}
