from __future__ import annotations

PERSONALIZED_FEED_SOURCE_KEY = "feed_source"
PERSONALIZED_FEED_ITEMS_KEY = "items"

PERSONALIZED_FEED_SOURCE_FOR_YOU = "for_you"
PERSONALIZED_FEED_SOURCE_FOLLOWING = "following"

PERSONALIZED_FEED_ALLOWED_SOURCES = frozenset(
    {
        PERSONALIZED_FEED_SOURCE_FOR_YOU,
        PERSONALIZED_FEED_SOURCE_FOLLOWING,
    }
)

__all__ = [
    "PERSONALIZED_FEED_ALLOWED_SOURCES",
    "PERSONALIZED_FEED_ITEMS_KEY",
    "PERSONALIZED_FEED_SOURCE_FOLLOWING",
    "PERSONALIZED_FEED_SOURCE_FOR_YOU",
    "PERSONALIZED_FEED_SOURCE_KEY",
]
