from __future__ import annotations

PLAYER_EVOLVED = "PLAYER_EVOLVED"
MATCH_COMPLETED = "MATCH_COMPLETED"
COMPETITION_ADVANCED = "COMPETITION_ADVANCED"
DYNASTY_UPDATED = "DYNASTY_UPDATED"
REGEN_PROMOTED = "REGEN_PROMOTED"

GLOBAL_MEMORY_PROJECTION = "global_memory"

__all__ = [
    "COMPETITION_ADVANCED",
    "DYNASTY_UPDATED",
    "GLOBAL_MEMORY_PROJECTION",
    "MATCH_COMPLETED",
    "PLAYER_EVOLVED",
    "REGEN_PROMOTED",
]
