from __future__ import annotations

EXPECTED_REGISTERED_MODULES = {
    "leagues",
    "champions_league",
    "academy",
    "ai_manager",
    "world_super_cup",
    "fast_cups",
    "match_engine",
    "matches",
    "simulation_matchmaking",
    "ultimate_league",
    "manager_marketplace",
    "predictions",
    "club_finance",
    "live_ops",
    "canonical_clubs",
    "competitive_integrity",
    "club_identity",
    "replay_archive",
    "notifications",
    "notifications_admin",
    "regen_universe",
    "football_universe",
    "broadcast_rights",
    "ownership_groups",
    "real_world_hub",
    "real_world_hub_admin",
    "gtex_universe",
    "federations",
    "federations_admin",
}

MATCH_ENGINE_OPENAPI_PRESENT_PATHS = [
    "/match-engine/replay",
    "/match-engine/summary",
]

CREATOR_MEDIA_OPENAPI_PRESENT_PATHS = [
    "/api/creators/profile",
    "/api/v1/creators/profile",
    "/api/creators/profile/me",
    "/api/v1/creators/profile/me",
    "/api/creators/me/summary",
    "/api/v1/creators/me/summary",
    "/api/creators/me/insights",
    "/api/v1/creators/me/insights",
    "/api/creators/me/copilot/analyze",
    "/api/v1/creators/me/copilot/analyze",
    "/api/creators/{handle}",
    "/api/v1/creators/{handle}",
    "/creators/me/insights",
    "/creators/me/copilot/analyze",
    "/api/creator/verify-email",
    "/api/v1/creator/verify-email",
    "/api/creator/apply",
    "/api/v1/creator/apply",
    "/api/creator/clubs/{club_id}/fan-share-market",
    "/api/v1/creator/clubs/{club_id}/fan-share-market",
    "/api/creator/clubs/{club_id}/fan-share-market/holding",
    "/api/v1/creator/clubs/{club_id}/fan-share-market/holding",
    "/api/admin/creator/fan-share-market/control",
    "/api/v1/admin/creator/fan-share-market/control",
    "/api/v1/media-engine/me/clip-earnings",
    "/api/v1/media-engine/creator-league/broadcast-modes",
    "/api/v1/admin/media-engine/creator-league/stadium-controls",
    "/media-engine/downloads/{token}",
]

CREATOR_MEDIA_OPENAPI_ABSENT_PATHS = [
    "/creators/{handle}",
    "/api/creator/profile",
    "/api/v1/creator/profile",
    "/api/creator/profile/me",
    "/api/v1/creator/profile/me",
    "/api/creator/me/summary",
    "/api/v1/creator/me/summary",
    "/api/creator/me/finance",
    "/api/v1/creator/me/finance",
    "/api/creators/apply",
    "/api/v1/creators/apply",
    "/api/creators/application",
    "/api/v1/creators/application",
    "/api/creators/verify-email",
    "/api/v1/creators/verify-email",
    "/api/creators/verify-phone",
    "/api/v1/creators/verify-phone",
    "/api/creators/clubs/{club_id}/fan-share-market",
    "/api/v1/creators/clubs/{club_id}/fan-share-market",
    "/api/creators/me/clip-earnings",
    "/api/v1/creators/me/clip-earnings",
    "/api/creator/me/clip-earnings",
    "/api/v1/creator/me/clip-earnings",
]

API_ONLY_FAMILY_OPENAPI_PRESENT_PATHS = [
    "/api/gift-engine/send",
    "/api/gift-engine/me/summary",
    "/api/v1/gift-engine/send",
    "/api/v1/gift-engine/me/summary",
    "/api/reward-engine/me/settlements",
    "/api/reward-engine/me/summary",
    "/api/v1/reward-engine/me/settlements",
    "/api/v1/reward-engine/me/summary",
    "/api/admin/reward-engine/settlements",
    "/api/v1/admin/reward-engine/settlements",
    "/api/admin/reward-engine/promo-pool/credits",
    "/api/v1/admin/reward-engine/promo-pool/credits",
    "/api/integrity-engine/me/score",
    "/api/integrity-engine/me/incidents",
    "/api/v1/integrity-engine/me/score",
    "/api/v1/integrity-engine/me/incidents",
    "/api/admin/integrity-engine/scan",
    "/api/v1/admin/integrity-engine/scan",
    "/api/admin/integrity-engine/incidents/{incident_id}/resolve",
    "/api/v1/admin/integrity-engine/incidents/{incident_id}/resolve",
    "/api/moderation/reports",
    "/api/moderation/me/reports",
    "/api/v1/moderation/reports",
    "/api/v1/moderation/me/reports",
    "/api/admin/moderation/reports",
    "/api/v1/admin/moderation/reports",
    "/api/admin/moderation/reports/summary",
    "/api/v1/admin/moderation/reports/summary",
    "/api/admin/moderation/reports/{report_id}/assign",
    "/api/v1/admin/moderation/reports/{report_id}/assign",
    "/api/admin/moderation/reports/{report_id}/resolve",
    "/api/v1/admin/moderation/reports/{report_id}/resolve",
    "/api/sponsorship/placements",
    "/api/sponsorship/clubs/{club_id}/contracts",
    "/api/v1/sponsorship/placements",
    "/api/v1/sponsorship/clubs/{club_id}/contracts",
    "/api/admin/sponsorship/packages",
    "/api/v1/admin/sponsorship/packages",
    "/api/admin/sponsorship/contracts/{contract_id}/review",
    "/api/v1/admin/sponsorship/contracts/{contract_id}/review",
    "/api/daily-challenges",
    "/api/daily-challenges/me",
    "/api/v1/daily-challenges",
    "/api/v1/daily-challenges/me",
    "/api/streamer-tournaments",
    "/api/streamer-tournaments/{tournament_id}",
    "/api/v1/streamer-tournaments",
    "/api/v1/streamer-tournaments/{tournament_id}",
    "/api/admin/streamer-tournaments/policy",
    "/api/v1/admin/streamer-tournaments/policy",
]

API_ONLY_FAMILY_OPENAPI_ABSENT_PATHS = [
    "/gift-engine/send",
    "/gift-engine/me/summary",
    "/reward-engine/me/settlements",
    "/reward-engine/me/summary",
    "/admin/reward-engine/settlements",
    "/admin/reward-engine/promo-pool/credits",
    "/integrity-engine/me/score",
    "/integrity-engine/me/incidents",
    "/admin/integrity-engine/scan",
    "/admin/integrity-engine/incidents/{incident_id}/resolve",
    "/moderation/reports",
    "/moderation/me/reports",
    "/admin/moderation/reports",
    "/admin/moderation/reports/summary",
    "/admin/moderation/reports/{report_id}/assign",
    "/admin/moderation/reports/{report_id}/resolve",
    "/sponsorship/placements",
    "/sponsorship/clubs/{club_id}/contracts",
    "/admin/sponsorship/packages",
    "/admin/sponsorship/contracts/{contract_id}/review",
    "/daily-challenges",
    "/daily-challenges/me",
    "/streamer-tournaments",
    "/streamer-tournaments/{tournament_id}",
    "/admin/streamer-tournaments/policy",
]

NAMESPACED_OPENAPI_PRESENT_PATHS = [
    "/api/notifications/me",
    "/api/v1/notifications/me",
    "/api/notifications/preferences",
    "/api/v1/notifications/preferences",
    "/api/notifications/subscriptions",
    "/api/v1/notifications/subscriptions",
    "/api/notifications/announcements",
    "/api/v1/notifications/announcements",
    "/api/admin/notifications/announcements",
    "/api/v1/admin/notifications/announcements",
    "/api/admin/world/cultures/{culture_key}",
    "/api/admin/world/clubs/{club_id}/context",
    "/api/admin/world/narratives/{narrative_slug}",
    "/api/v1/admin/world/cultures/{culture_key}",
    "/api/v1/admin/world/clubs/{club_id}/context",
    "/api/v1/admin/world/narratives/{narrative_slug}",
    "/api/community/digest",
    "/api/v1/community/digest",
    "/api/community/watchlist",
    "/api/v1/community/watchlist",
    "/api/community/live-threads",
    "/api/v1/community/live-threads",
    "/api/community/private-messages/threads",
    "/api/v1/community/private-messages/threads",
    "/api/governance/proposals",
    "/api/v1/governance/proposals",
    "/api/admin/governance/proposals/{proposal_id}/status",
    "/api/v1/admin/governance/proposals/{proposal_id}/status",
    "/api/hosted-competitions",
    "/api/hosted-competitions/templates",
    "/api/v1/hosted-competitions",
    "/api/v1/hosted-competitions/templates",
    "/api/admin/hosted-competitions/seed",
    "/api/v1/admin/hosted-competitions/seed",
    "/api/fan-wars/leaderboards/{board_type}",
    "/api/fan-wars/profiles/{profile_id}/dashboard",
    "/api/v1/fan-wars/leaderboards/{board_type}",
    "/api/v1/fan-wars/profiles/{profile_id}/dashboard",
    "/api/admin/fan-wars/profiles",
    "/api/v1/admin/fan-wars/profiles",
    "/api/calendar-engine/dashboard",
    "/api/calendar-engine/seasons",
    "/api/v1/calendar-engine/dashboard",
    "/api/v1/calendar-engine/seasons",
    "/api/events/today",
    "/api/v1/events/today",
    "/api/admin/calendar-engine/seasons",
    "/api/v1/admin/calendar-engine/seasons",
    "/api/admin/calendar-engine/hosted-competitions/{competition_id}/launch",
    "/api/v1/admin/calendar-engine/hosted-competitions/{competition_id}/launch",
    "/api/national-team-engine/competitions",
    "/api/national-team-engine/rankings",
    "/api/v1/national-team-engine/competitions",
    "/api/v1/national-team-engine/rankings",
    "/api/admin/national-team-engine/competitions",
    "/api/v1/admin/national-team-engine/competitions",
    "/api/story-feed",
    "/api/story-feed/digest",
    "/api/v1/story-feed",
    "/api/v1/story-feed/digest",
    "/api/admin/story-feed",
    "/api/v1/admin/story-feed",
    "/api/discovery/home",
    "/api/discovery/search",
    "/api/v1/discovery/home",
    "/api/v1/discovery/search",
    "/api/admin/discovery/featured-rails",
    "/api/v1/admin/discovery/featured-rails",
]

NAMESPACED_OPENAPI_ABSENT_PATHS = [
    "/notifications/me",
    "/notifications/preferences",
    "/notifications/subscriptions",
    "/notifications/announcements",
    "/admin/notifications/announcements",
    "/admin/world/cultures/{culture_key}",
    "/admin/world/clubs/{club_id}/context",
    "/admin/world/narratives/{narrative_slug}",
    "/community/digest",
    "/community/watchlist",
    "/community/live-threads",
    "/community/private-messages/threads",
    "/governance/proposals",
    "/admin/governance/proposals/{proposal_id}/status",
    "/hosted-competitions",
    "/hosted-competitions/templates",
    "/admin/hosted-competitions/seed",
    "/fan-wars/leaderboards/{board_type}",
    "/fan-wars/profiles/{profile_id}/dashboard",
    "/admin/fan-wars/profiles",
    "/calendar-engine/dashboard",
    "/calendar-engine/seasons",
    "/events/today",
    "/admin/calendar-engine/seasons",
    "/admin/calendar-engine/hosted-competitions/{competition_id}/launch",
    "/national-team-engine/competitions",
    "/national-team-engine/rankings",
    "/admin/national-team-engine/competitions",
    "/story-feed",
    "/story-feed/digest",
    "/admin/story-feed",
    "/discovery/home",
    "/discovery/search",
    "/admin/discovery/featured-rails",
]

PUBLIC_MISC_OPENAPI_PRESENT_PATHS = [
    "/broadcast/{match_id}",
    "/broadcast-rights/competitions/{competition_id}",
    "/broadcast-rights/matches/{match_id}/access",
    "/admin/broadcast-rights/jobs/run",
    "/fans/{club_id}",
    "/club/identity",
    "/media",
    "/ownership-groups",
    "/ownership-groups/transfers/validate",
    "/admin/ownership-groups/reputation-cycle",
    "/real-world/providers",
    "/real-world/hybrid-players",
    "/real-world/events",
    "/admin/real-world/providers",
    "/career/create",
    "/career/retire",
    "/career/{user_id}",
    "/sync/update",
    "/api/federations",
    "/api/v1/federations",
    "/api/admin/federations/run-jobs",
    "/api/v1/admin/federations/run-jobs",
    "/api/clubs/{club_id}/reputation",
    "/api/clubs/{club_id}/dynasty",
    "/api/clubs/{club_id}/identity",
    "/regen-universe/awards",
    "/regen-universe/rising-stars",
    "/regen-universe/player/{player_id}",
    "/regen-universe/bloodlines",
    "/regen-universe/scouting-feed",
    "/regen-universe/youth-tournaments",
    "/regen-universe/youth-tournaments/{tournament_id}",
    "/admin/regen-universe/youth-tournaments",
    "/admin/regen-universe/jobs/story-regeneration",
    "/admin/regen-universe/jobs/rivalry-detection",
    "/admin/regen-universe/jobs/dna-evolution",
    "/admin/regen-universe/jobs/tournament-scheduling",
    "/admin/ops/fan-updates",
    "/admin/ops/media-generation",
    "/admin/ops/identity-evolution",
    "/players/{player_id}/story",
    "/players/{player_id}/dna",
    "/players/{player_id}/rivalries",
    "/replays/public/featured",
    "/api/wallet",
    "/api/wallet/transactions",
    "/api/wallet/top-up/initiate",
    "/api/wallet/top-up/verify",
    "/api/wallets",
    "/api/wallets/transactions",
    "/api/wallets/top-up/initiate",
    "/api/wallets/top-up/verify",
    "/api/v1/wallet",
    "/api/v1/wallet/transactions",
    "/api/v1/wallet/top-up/initiate",
    "/api/v1/wallet/top-up/verify",
    "/api/v1/wallets",
    "/api/v1/wallets/transactions",
    "/api/v1/wallets/top-up/initiate",
    "/api/v1/wallets/top-up/verify",
]

PUBLIC_MISC_OPENAPI_ABSENT_PATHS = [
    "/federations",
    "/federations/rankings",
    "/federations/{federation_id}/governance",
    "/admin/federations/run-jobs",
    "/match-viewer/{match_key}",
]

CORE_OPENAPI_PRESENT_PATHS = [
    "/leagues/register",
    "/champions-league/qualification-map",
    "/academy/season-summary",
    "/ai-manager/autopilot/run",
    "/world-super-cup/countdown",
    "/fast-cups/upcoming",
    "/matches/start",
    "/matches/complete",
    "/matches/{match_id}/replay",
    "/matches/{match_id}/analysis",
    "/predictions",
    "/predictions/leaderboard",
    "/finance",
    "/sponsors",
    "/season-pass",
    "/season-pass/claim",
    "/live-events",
    "/api/predictions",
    "/api/finance",
    "/api/season-pass",
    "/managers",
    "/managers/leaderboard",
    "/simulation-matchmaking/quick-game",
    "/ultimate-league/tiers",
    "/ultimate-league/tournaments",
    "/api/competitive-integrity/managers",
    "/api/competitive-integrity/matches",
    "/api/competitive-integrity/fast-game/runs",
]

VALID_CALENDAR_SEASON_CREATE_PAYLOAD = {
    "season_key": "global-2026",
    "title": "Global Season 2026",
    "starts_on": "2026-01-01",
    "ends_on": "2026-12-31",
    "status": "draft",
}

VALID_GOVERNANCE_STATUS_PAYLOAD = {
    "status": "accepted",
    "result_summary": "Closed by admin review.",
}

VALID_NATIONAL_TEAM_COMPETITION_CREATE_PAYLOAD = {
    "key": "world-cup-2026",
    "title": "World Cup 2026",
    "season_label": "2026",
    "region_type": "global",
    "age_band": "senior",
    "format_type": "cup",
    "status": "draft",
}

VALID_STORY_FEED_PUBLISH_PAYLOAD = {
    "story_type": "match_update",
    "title": "Opening day story",
    "body": "A featured update for the new season.",
    "audience": "public",
}

VALID_REWARD_SETTLEMENT_PAYLOAD = {
    "user_id": "user-1",
    "competition_key": "friendly-cup",
    "title": "Friendly Cup reward",
    "gross_amount": "100.00",
    "reward_source": "gtex_promotional_pool",
}

VALID_PROMO_POOL_CREDIT_PAYLOAD = {
    "amount": "50.00",
    "unit": "coin",
    "reference": "promo-seed",
}

VALID_INTEGRITY_SCAN_PAYLOAD = {
    "repeated_gift_threshold": 3,
    "reward_cluster_threshold": 3,
    "lookback_limit": 200,
}

VALID_CREATOR_COPILOT_PAYLOAD = {
    "title": "Goal montage",
    "duration_seconds": 18.0,
    "event_type": "goal",
    "preferred_format": "instant",
}

VALID_CAREER_RETIRE_PAYLOAD = {
    "legacy_role": "hall_of_fame",
    "legacy_headline": "A decorated career comes to a close.",
}

VALID_SYNC_UPDATE_PAYLOAD = {
    "provider_name": "manual-sync",
    "provider_endpoint": "manual://sync",
    "optional_sync": True,
    "mirror_into_gtex": True,
}

VALID_AUTOPILOT_RUN_PAYLOAD = {
    "club_id": "club-1",
    "user_last_active_hours": 24.0,
    "club_strength": 72,
    "opponent": {
        "club_name": "Rivals FC",
        "strength": 70,
        "tactical_style": "balanced",
    },
    "squad": [
        {
            "player_id": f"player-{index + 1}",
            "name": f"Player {index + 1}",
            "primary_position": "CM",
            "secondary_positions": ["CDM"] if index % 2 == 0 else [],
            "rating": 68 + (index % 5),
            "potential": 74 + (index % 5),
            "age": 21 + (index % 6),
            "fatigue": 0.2,
            "stamina": 0.8,
            "form": 0.7,
            "injury_risk": 0.1,
            "wage_cost": 1200 + index * 50,
            "transfer_value": 50000 + index * 2500,
            "morale": 0.65,
        }
        for index in range(11)
    ],
    "finance": {
        "revenue": 250000,
        "wage_bill": 80000,
        "transfer_budget": 60000,
        "cash_balance": 150000,
        "scouting_budget": 10000,
        "training_budget": 8000,
    },
}

MOUNTED_MODULE_ROUTE_CASES = [
    ("GET", "/world-super-cup/countdown", None, None, 200),
    ("GET", "/fast-cups/upcoming", None, None, 200),
    ("GET", "/replays/public/featured", None, None, 200),
    ("POST", "/leagues/register", {}, None, 422),
    ("POST", "/champions-league/qualification-map", {}, None, 422),
    ("POST", "/academy/season-summary", {}, None, 422),
    ("POST", "/ai-manager/autopilot/run", VALID_AUTOPILOT_RUN_PAYLOAD, None, 401),
    ("POST", "/match-engine/summary", {}, None, 422),
    ("POST", "/match-engine/replay", {}, None, 422),
    ("POST", "/matches/start", {}, None, 422),
    ("POST", "/matches/complete", {}, None, 422),
    ("GET", "/matches/nonexistent/replay", None, None, 404),
    ("GET", "/matches/nonexistent/analysis", None, None, 404),
    ("GET", "/predictions", None, None, 401),
    ("GET", "/finance", None, None, 401),
    ("GET", "/sponsors", None, None, 401),
    ("GET", "/season-pass", None, None, 401),
    ("GET", "/live-events", None, None, 401),
    ("GET", "/managers", None, None, 200),
    ("POST", "/simulation-matchmaking/quick-game", {}, None, 422),
    ("GET", "/ultimate-league/tiers", None, None, 200),
    ("POST", "/ultimate-league/tournaments", {}, None, 422),
    ("GET", "/api/competitive-integrity/managers", None, None, 401),
    ("GET", "/api/notifications/me", None, None, 401),
    ("GET", "/api/admin/notifications/announcements", None, None, 401),
    ("GET", "/admin/notifications/announcements", None, None, 404),
    ("GET", "/api/community/digest", None, None, 401),
    ("GET", "/community/digest", None, None, 404),
    ("GET", "/api/governance/proposals", None, None, 200),
    ("POST", "/api/admin/governance/proposals/nonexistent/status", VALID_GOVERNANCE_STATUS_PAYLOAD, None, 401),
    ("GET", "/governance/proposals", None, None, 404),
    ("POST", "/admin/governance/proposals/nonexistent/status", {}, None, 404),
    ("GET", "/api/hosted-competitions", None, None, 200),
    ("GET", "/api/v1/hosted-competitions", None, None, 200),
    ("GET", "/hosted-competitions", None, None, 404),
    ("GET", "/api/calendar-engine/dashboard", None, None, 200),
    ("GET", "/api/v1/calendar-engine/dashboard", None, None, 200),
    ("GET", "/calendar-engine/dashboard", None, None, 404),
    ("GET", "/api/events/today", None, None, 200),
    ("GET", "/api/v1/events/today", None, None, 200),
    ("GET", "/events/today", None, None, 404),
    ("POST", "/api/admin/calendar-engine/seasons", VALID_CALENDAR_SEASON_CREATE_PAYLOAD, None, 401),
    ("POST", "/admin/calendar-engine/seasons", {}, None, 404),
    ("GET", "/api/national-team-engine/competitions", None, None, 200),
    ("GET", "/api/v1/national-team-engine/competitions", None, None, 200),
    ("GET", "/national-team-engine/competitions", None, None, 404),
    ("POST", "/api/admin/national-team-engine/competitions", VALID_NATIONAL_TEAM_COMPETITION_CREATE_PAYLOAD, None, 401),
    ("POST", "/api/v1/admin/national-team-engine/competitions", VALID_NATIONAL_TEAM_COMPETITION_CREATE_PAYLOAD, None, 401),
    ("POST", "/admin/national-team-engine/competitions", {}, None, 404),
    ("GET", "/api/story-feed", None, None, 200),
    ("GET", "/api/v1/story-feed", None, None, 200),
    ("GET", "/story-feed", None, None, 404),
    ("POST", "/api/admin/story-feed", VALID_STORY_FEED_PUBLISH_PAYLOAD, None, 401),
    ("POST", "/api/v1/admin/story-feed", VALID_STORY_FEED_PUBLISH_PAYLOAD, None, 401),
    ("POST", "/admin/story-feed", {}, None, 404),
    ("GET", "/api/discovery/home", None, None, 401),
    ("GET", "/api/v1/discovery/home", None, None, 401),
    ("GET", "/discovery/home", None, None, 404),
    ("GET", "/api/admin/discovery/featured-rails", None, None, 401),
    ("GET", "/api/v1/admin/discovery/featured-rails", None, None, 401),
    ("GET", "/admin/discovery/featured-rails", None, None, 404),
    ("GET", "/api/gift-engine/me/summary", None, None, 401),
    ("GET", "/api/v1/gift-engine/me/summary", None, None, 401),
    ("GET", "/gift-engine/me/summary", None, None, 404),
    ("POST", "/api/sponsorship/placements", {"competition_id": "friendly-cup", "stage_name": "Group Stage", "region_code": "NA"}, None, 200),
    ("POST", "/api/v1/sponsorship/placements", {"competition_id": "friendly-cup", "stage_name": "Group Stage", "region_code": "NA"}, None, 200),
    ("POST", "/sponsorship/placements", {"competition_id": "friendly-cup", "stage_name": "Group Stage", "region_code": "NA"}, None, 404),
    ("GET", "/api/admin/sponsorship/packages", None, None, 401),
    ("GET", "/api/v1/admin/sponsorship/packages", None, None, 401),
    ("GET", "/admin/sponsorship/packages", None, None, 404),
    ("GET", "/broadcast/nonexistent", None, None, 404),
    ("GET", "/broadcast-rights/competitions/nonexistent", None, None, 404),
    ("GET", "/broadcast-rights/matches/nonexistent/access", None, None, 401),
    ("POST", "/admin/broadcast-rights/jobs/run", None, None, 401),
    ("GET", "/fans/nonexistent", None, None, 404),
    ("GET", "/club/identity", None, {"club_id": "nonexistent"}, 404),
    ("GET", "/media", None, None, 200),
    ("GET", "/ownership-groups", None, None, 401),
    (
        "GET",
        "/ownership-groups/transfers/validate",
        None,
        {
            "player_id": "nonexistent",
            "selling_club_id": "nonexistent",
            "buying_club_id": "nonexistent",
            "bid_amount": "1.0000",
        },
        401,
    ),
    ("POST", "/admin/ownership-groups/reputation-cycle", None, None, 401),
    ("POST", "/admin/ops/fan-updates", None, None, 401),
    ("POST", "/admin/ops/media-generation", None, None, 401),
    ("POST", "/admin/ops/identity-evolution", None, None, 401),
    ("GET", "/real-world/events", None, None, 200),
    ("GET", "/career/nonexistent", None, None, 404),
    ("POST", "/career/retire", VALID_CAREER_RETIRE_PAYLOAD, None, 401),
    ("POST", "/sync/update", VALID_SYNC_UPDATE_PAYLOAD, None, 401),
    ("GET", "/regen-universe/awards", None, None, 200),
    ("GET", "/regen-universe/rising-stars", None, None, 200),
    ("GET", "/regen-universe/bloodlines", None, None, 200),
    ("GET", "/regen-universe/scouting-feed", None, None, 200),
    ("GET", "/regen-universe/youth-tournaments", None, None, 200),
    ("GET", "/regen-universe/youth-tournaments/nonexistent", None, None, 404),
    ("GET", "/players/nonexistent/story", None, None, 404),
    ("GET", "/players/nonexistent/dna", None, None, 404),
    ("GET", "/players/nonexistent/rivalries", None, None, 404),
    ("GET", "/api/wallet", None, None, 401),
    ("GET", "/api/wallet/transactions", None, None, 401),
    ("GET", "/api/v1/wallet", None, None, 401),
    ("GET", "/api/v1/wallet/transactions", None, None, 401),
    ("GET", "/match-viewer/nonexistent", None, None, 404),
]

REWARD_AND_INTEGRITY_ROUTE_CASES = [
    ("GET", "/api/reward-engine/me/summary", None, 401),
    ("GET", "/api/v1/reward-engine/me/summary", None, 401),
    ("GET", "/reward-engine/me/summary", None, 404),
    ("POST", "/api/admin/reward-engine/settlements", VALID_REWARD_SETTLEMENT_PAYLOAD, 401),
    ("POST", "/api/v1/admin/reward-engine/settlements", VALID_REWARD_SETTLEMENT_PAYLOAD, 401),
    ("POST", "/admin/reward-engine/settlements", {}, 404),
    ("POST", "/api/admin/reward-engine/promo-pool/credits", VALID_PROMO_POOL_CREDIT_PAYLOAD, 401),
    ("POST", "/api/v1/admin/reward-engine/promo-pool/credits", VALID_PROMO_POOL_CREDIT_PAYLOAD, 401),
    ("POST", "/admin/reward-engine/promo-pool/credits", {}, 404),
    ("GET", "/api/integrity-engine/me/score", None, 401),
    ("GET", "/api/v1/integrity-engine/me/score", None, 401),
    ("GET", "/integrity-engine/me/score", None, 404),
    ("POST", "/api/admin/integrity-engine/scan", VALID_INTEGRITY_SCAN_PAYLOAD, 401),
    ("POST", "/api/v1/admin/integrity-engine/scan", VALID_INTEGRITY_SCAN_PAYLOAD, 401),
    ("POST", "/admin/integrity-engine/scan", {}, 404),
]

DAILY_CHALLENGES_AND_STREAMER_ROUTE_CASES = [
    ("GET", "/api/daily-challenges", None, 200),
    ("GET", "/api/v1/daily-challenges", None, 200),
    ("GET", "/daily-challenges", None, 404),
    ("GET", "/api/daily-challenges/me", None, 401),
    ("GET", "/api/v1/daily-challenges/me", None, 401),
    ("GET", "/daily-challenges/me", None, 404),
    ("POST", "/api/daily-challenges/daily-login/claim", None, 401),
    ("POST", "/api/v1/daily-challenges/daily-login/claim", None, 401),
    ("POST", "/daily-challenges/daily-login/claim", None, 404),
    ("GET", "/api/streamer-tournaments", None, 200),
    ("GET", "/api/v1/streamer-tournaments", None, 200),
    ("GET", "/streamer-tournaments", None, 404),
    ("GET", "/api/admin/streamer-tournaments/policy", None, 401),
    ("GET", "/api/v1/admin/streamer-tournaments/policy", None, 401),
    ("GET", "/admin/streamer-tournaments/policy", None, 404),
]

MODERATION_ROUTE_CASES = [
    (
        "POST",
        "/api/moderation/reports",
        {
            "target_type": "user",
            "target_id": "user-2",
            "reason_code": "abuse",
            "description": "Suspicious abuse pattern detected.",
        },
        401,
    ),
    (
        "POST",
        "/api/v1/moderation/reports",
        {
            "target_type": "user",
            "target_id": "user-2",
            "reason_code": "abuse",
            "description": "Suspicious abuse pattern detected.",
        },
        401,
    ),
    (
        "POST",
        "/moderation/reports",
        {
            "target_type": "user",
            "target_id": "user-2",
            "reason_code": "abuse",
            "description": "Suspicious abuse pattern detected.",
        },
        404,
    ),
    ("GET", "/api/moderation/me/reports", None, 401),
    ("GET", "/api/v1/moderation/me/reports", None, 401),
    ("GET", "/moderation/me/reports", None, 404),
    ("GET", "/api/admin/moderation/reports", None, 401),
    ("GET", "/api/v1/admin/moderation/reports", None, 401),
    ("GET", "/admin/moderation/reports", None, 404),
]

CREATOR_AND_MEDIA_ROUTE_CASES = [
    ("GET", "/api/creators/nonexistent-handle", None, 404),
    ("GET", "/api/v1/creators/nonexistent-handle", None, 404),
    ("GET", "/creators/nonexistent-handle", None, 404),
    ("GET", "/api/creators/profile/me", None, 401),
    ("GET", "/api/v1/creators/profile/me", None, 401),
    ("GET", "/api/creators/me/insights", None, 401),
    ("GET", "/api/v1/creators/me/insights", None, 401),
    ("POST", "/api/creators/me/copilot/analyze", VALID_CREATOR_COPILOT_PAYLOAD, 401),
    ("POST", "/api/v1/creators/me/copilot/analyze", VALID_CREATOR_COPILOT_PAYLOAD, 401),
    ("GET", "/creators/me/insights", None, 401),
    ("POST", "/creators/me/copilot/analyze", VALID_CREATOR_COPILOT_PAYLOAD, 401),
    ("GET", "/api/creator/profile/me", None, 404),
    ("GET", "/api/v1/creator/profile/me", None, 404),
    ("GET", "/api/creator/me/summary", None, 404),
    ("GET", "/api/v1/creator/me/summary", None, 404),
    ("GET", "/api/creator/me/finance", None, 404),
    ("GET", "/api/v1/creator/me/finance", None, 404),
    ("POST", "/api/creator/verify-email", None, 401),
    ("POST", "/api/v1/creator/verify-email", None, 401),
    ("POST", "/api/creators/apply", {}, 405),
    ("POST", "/api/v1/creators/apply", {}, 405),
    ("GET", "/api/creator/clubs/club-1/fan-share-market/holding", None, 401),
    ("GET", "/api/v1/creator/clubs/club-1/fan-share-market/holding", None, 401),
    ("GET", "/api/creators/clubs/club-1/fan-share-market/holding", None, 404),
    ("GET", "/api/v1/creators/clubs/club-1/fan-share-market/holding", None, 404),
    ("GET", "/api/v1/media-engine/me/clip-earnings", None, 401),
    ("GET", "/api/v1/media-engine/creator-league/season-passes/me", None, 401),
    ("GET", "/api/v1/admin/media-engine/creator-league/stadium-controls", None, 401),
    ("GET", "/api/creators/me/clip-earnings", None, 404),
    ("GET", "/api/v1/creators/me/clip-earnings", None, 404),
]

LIVE_BROADCAST_AND_MATCH_VIEWER_HYDRATION_ROUTE_CASES = [
    ("/api/broadcast/home", 200),
    ("/api/match-viewer/nonexistent", 404),
]
