apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gtex

resources:
  - namespace.yaml
  - configmap.yaml
  - api.yaml
  - outbox-relay.yaml
  - simulation-worker.yaml
  - projection-worker.yaml
  - ingress.yaml
  - hpa-api.yaml

