apiVersion: v1
kind: Secret
metadata:
  name: gtex-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://gtex:change-me@postgres-rw.gtex.svc.cluster.local:5432/gtex
  GTE_REDIS_URL: redis://redis.gtex.svc.cluster.local:6379/0
  GTE_AUTH_SECRET: change-me
  GTE_MEDIA_SIGNING_SECRET: change-me
  BREVO_SMTP_PASSWORD: change-me
  GTE_PAYSTACK_SECRET_KEY: change-me
  GTE_PAYSTACK_WEBHOOK_SECRET: change-me
  GTE_KORAPAY_SECRET_KEY: change-me
  GTE_KORAPAY_WEBHOOK_SECRET: change-me
  GTE_KORAPAY_REDIRECT_URL: https://<your-web-frontend-domain>/payment/redirect
  GTE_KORAPAY_NOTIFICATION_URL: https://<your-production-backend-domain>/integrations/payments/korapay/webhook
